// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Optional parameters for AiManager.getAgentDefault. */
export interface AiManagerGetAgentDefaultOptions {
  language?: string;
  model?: string;
}

/** Operations for the "ai" API area. */
export class AiManager {
  constructor(private readonly session: runtime.Client) {}

  async ask(body: models.schemas.AiAsk): Promise<models.schemas.AiResponseFull> {
    let url = this.session.baseUrl("api");
    url += "/ai";
    url += "/ask";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiResponseFull;
  }

  async createTextGen(body: models.schemas.AiTextGen): Promise<models.schemas.AiResponse> {
    let url = this.session.baseUrl("api");
    url += "/ai";
    url += "/text_gen";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiResponse;
  }

  async getAgentDefault(mode: models.schemas.GetAgentDefaultMode, opts?: AiManagerGetAgentDefaultOptions): Promise<models.schemas.AiAgent> {
    let url = this.session.baseUrl("api");
    url += "/ai_agent_default";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "mode", mode);
    const options = opts ?? {};
    if (options.language !== undefined) {
      req = runtime.withQuery(req, "language", options.language);
    }
    if (options.model !== undefined) {
      req = runtime.withQuery(req, "model", options.model);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiAgent;
  }

  async extract(body: models.schemas.AiExtract): Promise<models.schemas.AiResponse> {
    let url = this.session.baseUrl("api");
    url += "/ai";
    url += "/extract";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiResponse;
  }

  async createExtractStructured(body: models.schemas.AiExtractStructured): Promise<models.schemas.AiExtractStructuredResponse> {
    let url = this.session.baseUrl("api");
    url += "/ai";
    url += "/extract_structured";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiExtractStructuredResponse;
  }
}
