// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for AiStudioManager.listAiAgents. */
export interface AiStudioManagerListAiAgentsOptions {
  mode?: Array<string>;
  fields?: Array<string>;
  agent_state?: Array<string>;
  include_box_default?: boolean;
  marker?: string;
  limit?: number;
}

/** Optional parameters for AiStudioManager.getAiAgent. */
export interface AiStudioManagerGetAiAgentOptions {
  fields?: Array<string>;
}

/** Operations for the "ai_studio" API area. */
export class AiStudioManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.AiSingleAgentResponseFull` across pages, threading the marker cursor. */
  async *listAiAgents(opts?: AiStudioManagerListAiAgentsOptions): AsyncIterableIterator<models.schemas.AiSingleAgentResponseFull> {
    const options: AiStudioManagerListAiAgentsOptions = { ...opts };
    for (;;) {
      const page = await this.listAiAgentsPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listAiAgentsPage(opts?: AiStudioManagerListAiAgentsOptions): Promise<models.schemas.AiMultipleAgentResponse> {
    let url = this.session.baseUrl("api");
    url += "/ai_agents";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.mode !== undefined) {
      req = runtime.withQuery(req, "mode", options.mode.join(','));
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.agent_state !== undefined) {
      req = runtime.withQuery(req, "agent_state", options.agent_state.join(','));
    }
    if (options.include_box_default !== undefined) {
      req = runtime.withQuery(req, "include_box_default", String(options.include_box_default));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiMultipleAgentResponse;
  }

  async createAiAgents(body: models.schemas.CreateAiAgent): Promise<models.schemas.AiSingleAgentResponseFull> {
    let url = this.session.baseUrl("api");
    url += "/ai_agents";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiSingleAgentResponseFull;
  }

  async getAiAgent(agentId: string, opts?: AiStudioManagerGetAiAgentOptions): Promise<models.schemas.AiSingleAgentResponseFull> {
    let url = this.session.baseUrl("api");
    url += "/ai_agents";
    url += '/' + pathEscape(agentId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiSingleAgentResponseFull;
  }

  async updateAiAgent(agentId: string, body: models.schemas.CreateAiAgent): Promise<models.schemas.AiSingleAgentResponseFull> {
    let url = this.session.baseUrl("api");
    url += "/ai_agents";
    url += '/' + pathEscape(agentId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AiSingleAgentResponseFull;
  }

  async deleteAiAgent(agentId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/ai_agents";
    url += '/' + pathEscape(agentId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
