// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for AppItemAssociationsManager.listFile. */
export interface AppItemAssociationsManagerListFileOptions {
  limit?: number;
  marker?: string;
  application_type?: string;
}

/** Optional parameters for AppItemAssociationsManager.listFolder. */
export interface AppItemAssociationsManagerListFolderOptions {
  limit?: number;
  marker?: string;
  application_type?: string;
}

/** Operations for the "app_item_associations" API area. */
export class AppItemAssociationsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.AppItemAssociation` across pages, threading the marker cursor. */
  async *listFile(fileId: string, opts?: AppItemAssociationsManagerListFileOptions): AsyncIterableIterator<models.schemas.AppItemAssociation> {
    const options: AppItemAssociationsManagerListFileOptions = { ...opts };
    for (;;) {
      const page = await this.listFilePage(fileId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFilePage(fileId: string, opts?: AppItemAssociationsManagerListFileOptions): Promise<models.schemas.AppItemAssociations> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/app_item_associations";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.application_type !== undefined) {
      req = runtime.withQuery(req, "application_type", options.application_type);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AppItemAssociations;
  }

  /** Iterate every `models.schemas.AppItemAssociation` across pages, threading the marker cursor. */
  async *listFolder(folderId: string, opts?: AppItemAssociationsManagerListFolderOptions): AsyncIterableIterator<models.schemas.AppItemAssociation> {
    const options: AppItemAssociationsManagerListFolderOptions = { ...opts };
    for (;;) {
      const page = await this.listFolderPage(folderId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFolderPage(folderId: string, opts?: AppItemAssociationsManagerListFolderOptions): Promise<models.schemas.AppItemAssociations> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/app_item_associations";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.application_type !== undefined) {
      req = runtime.withQuery(req, "application_type", options.application_type);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AppItemAssociations;
  }
}
