// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for ArchivesManager.list. */
export interface ArchivesManagerListOptions {
  limit?: number;
  marker?: string;
}

/** Operations for the "archives" API area. */
export class ArchivesManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.Archive` across pages, threading the marker cursor. */
  async *list(opts?: ArchivesManagerListOptions): AsyncIterableIterator<models.schemas.Archive> {
    const options: ArchivesManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: ArchivesManagerListOptions): Promise<models.schemas.Archives> {
    let url = this.session.baseUrl("api");
    url += "/archives";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Archives;
  }

  async create(body: models.schemas.ArchiveCreateRequest): Promise<models.schemas.Archive> {
    let url = this.session.baseUrl("api");
    url += "/archives";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Archive;
  }

  async update(archiveId: string, body: models.schemas.ArchiveUpdateRequest): Promise<models.schemas.Archive> {
    let url = this.session.baseUrl("api");
    url += "/archives";
    url += '/' + pathEscape(archiveId);
    let req = this.session.newRequest("PUT", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Archive;
  }

  async delete_(archiveId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/archives";
    url += '/' + pathEscape(archiveId);
    let req = this.session.newRequest("DELETE", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    await this.session.fetch(req);
  }
}
