// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { formEncode } from '../internal.js';

/** Optional parameters for AuthorizationManager.authorize. */
export interface AuthorizationManagerAuthorizeOptions {
  redirect_uri?: string;
  state?: string;
  scope?: string;
}

/** Operations for the "authorization" API area. */
export class AuthorizationManager {
  constructor(private readonly session: runtime.Client) {}

  async authorize(responseType: models.schemas.GetAuthorizeResponseType, clientId: string, opts?: AuthorizationManagerAuthorizeOptions): Promise<string> {
    let url = this.session.baseUrl("oauth_authorize");
    url += "/authorize";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "response_type", responseType);
    req = runtime.withQuery(req, "client_id", clientId);
    const options = opts ?? {};
    if (options.redirect_uri !== undefined) {
      req = runtime.withQuery(req, "redirect_uri", options.redirect_uri);
    }
    if (options.state !== undefined) {
      req = runtime.withQuery(req, "state", options.state);
    }
    if (options.scope !== undefined) {
      req = runtime.withQuery(req, "scope", options.scope);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return new TextDecoder().decode(data);
  }

  async createOauth2Token(body: models.schemas.PostOAuth2Token): Promise<models.schemas.AccessToken> {
    let url = this.session.baseUrl("api_root");
    url += "/oauth2";
    url += "/token";
    let req = this.session.newRequest("POST", url);
    const form: Array<[string, string]> = [["grant_type", body.grant_type]];
    if (body.client_id != null) {
      form.push(["client_id", body.client_id]);
    }
    if (body.client_secret != null) {
      form.push(["client_secret", body.client_secret]);
    }
    if (body.code != null) {
      form.push(["code", body.code]);
    }
    if (body.refresh_token != null) {
      form.push(["refresh_token", body.refresh_token]);
    }
    if (body.assertion != null) {
      form.push(["assertion", body.assertion]);
    }
    if (body.subject_token != null) {
      form.push(["subject_token", body.subject_token]);
    }
    if (body.subject_token_type != null) {
      form.push(["subject_token_type", body.subject_token_type]);
    }
    if (body.actor_token != null) {
      form.push(["actor_token", body.actor_token]);
    }
    if (body.actor_token_type != null) {
      form.push(["actor_token_type", body.actor_token_type]);
    }
    if (body.scope != null) {
      form.push(["scope", body.scope]);
    }
    if (body.resource != null) {
      form.push(["resource", body.resource]);
    }
    if (body.box_subject_type != null) {
      form.push(["box_subject_type", body.box_subject_type]);
    }
    if (body.box_subject_id != null) {
      form.push(["box_subject_id", body.box_subject_id]);
    }
    if (body.box_shared_link != null) {
      form.push(["box_shared_link", body.box_shared_link]);
    }
    req = runtime.withFormBody(req, new TextEncoder().encode(formEncode(form)));
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AccessToken;
  }

  async createOauth2TokenRefresh(body: models.schemas.PostOAuth2TokenRefreshAccessToken): Promise<models.schemas.AccessToken> {
    let url = this.session.baseUrl("api_root");
    url += "/oauth2";
    url += "/token";
    let req = this.session.newRequest("POST", url);
    const form: Array<[string, string]> = [["grant_type", body.grant_type], ["client_id", body.client_id], ["client_secret", body.client_secret], ["refresh_token", body.refresh_token]];
    req = runtime.withFormBody(req, new TextEncoder().encode(formEncode(form)));
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AccessToken;
  }

  async revokeOauth2(body: models.schemas.PostOAuth2Revoke): Promise<void> {
    let url = this.session.baseUrl("api_root");
    url += "/oauth2";
    url += "/revoke";
    let req = this.session.newRequest("POST", url);
    const form: Array<[string, string]> = [];
    if (body.client_id != null) {
      form.push(["client_id", body.client_id]);
    }
    if (body.client_secret != null) {
      form.push(["client_secret", body.client_secret]);
    }
    if (body.token != null) {
      form.push(["token", body.token]);
    }
    req = runtime.withFormBody(req, new TextEncoder().encode(formEncode(form)));
    await this.session.fetch(req);
  }
}
