// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for AutomateWorkflowsManager.list. */
export interface AutomateWorkflowsManagerListOptions {
  limit?: number;
  marker?: string;
}

/** Operations for the "automate_workflows" API area. */
export class AutomateWorkflowsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.AutomateWorkflowAction` across pages, threading the marker cursor. */
  async *list(folderId: string, opts?: AutomateWorkflowsManagerListOptions): AsyncIterableIterator<models.schemas.AutomateWorkflowAction> {
    const options: AutomateWorkflowsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(folderId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(folderId: string, opts?: AutomateWorkflowsManagerListOptions): Promise<models.schemas.AutomateWorkflows> {
    let url = this.session.baseUrl("api");
    url += "/automate_workflows";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "folder_id", folderId);
    const options = opts ?? {};
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    req = runtime.withHeader(req, "box-version", "2026.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AutomateWorkflows;
  }

  async start(workflowId: string, body: models.schemas.AutomateWorkflowStartRequest): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/automate_workflows";
    url += '/' + pathEscape(workflowId);
    url += "/start";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2026.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    await this.session.fetch(req);
  }
}
