// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "avatars" API area. */
export class AvatarsManager {
  constructor(private readonly session: runtime.Client) {}

  async getUserAvatar(userId: string): Promise<runtime.Stream> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    url += "/avatar";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    return runtime.responseStream(resp);
  }

  async createUserAvatar(userId: string, body: models.schemas.UserAvatarCreateRequest): Promise<models.schemas.UserAvatar> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    url += "/avatar";
    let req = this.session.newRequest("POST", url);
    const attributes = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withMultipartBody(req, attributes, 'file', runtime.Stream.empty());
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UserAvatar;
  }

  async deleteUserAvatar(userId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    url += "/avatar";
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
