// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for ChunkedUploadsManager.listFileUploadSessionParts. */
export interface ChunkedUploadsManagerListFileUploadSessionPartsOptions {
  offset?: number;
  limit?: number;
}

/** Optional parameters for ChunkedUploadsManager.commitFileUploadSession. */
export interface ChunkedUploadsManagerCommitFileUploadSessionOptions {
  "if-match"?: string;
  "if-none-match"?: string;
}

/** Operations for the "chunked_uploads" API area. */
export class ChunkedUploadsManager {
  constructor(private readonly session: runtime.Client) {}

  async createFileUploadSessions(body: models.schemas.FileUploadSessionsCreateRequest): Promise<models.schemas.UploadSession> {
    let url = this.session.baseUrl("upload");
    url += "/files";
    url += "/upload_sessions";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UploadSession;
  }

  async createFileByIdUploadSessions(fileId: string, body: models.schemas.FileIdUploadSessionsCreateRequest): Promise<models.schemas.UploadSession> {
    let url = this.session.baseUrl("upload");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/upload_sessions";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UploadSession;
  }

  async getFileUploadSession(uploadSessionId: string): Promise<models.schemas.UploadSession> {
    let url = this.session.baseUrl("upload_session");
    url += "/files";
    url += "/upload_sessions";
    url += '/' + pathEscape(uploadSessionId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UploadSession;
  }

  async updateFileUploadSession(uploadSessionId: string, digest: string, contentRange: string, body: Blob): Promise<models.schemas.UploadedPart> {
    let url = this.session.baseUrl("upload_session");
    url += "/files";
    url += "/upload_sessions";
    url += '/' + pathEscape(uploadSessionId);
    let req = this.session.newRequest("PUT", url);
    req = runtime.withHeader(req, "digest", digest);
    req = runtime.withHeader(req, "content-range", contentRange);
    void body;
    req = runtime.withStreamBody(req, runtime.Stream.empty(), 'application/octet-stream');
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UploadedPart;
  }

  async deleteFileUploadSession(uploadSessionId: string): Promise<void> {
    let url = this.session.baseUrl("upload_session");
    url += "/files";
    url += "/upload_sessions";
    url += '/' + pathEscape(uploadSessionId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  /** Iterate every `models.schemas.UploadPart` across pages, threading the offset cursor. */
  async *listFileUploadSessionParts(uploadSessionId: string, opts?: ChunkedUploadsManagerListFileUploadSessionPartsOptions): AsyncIterableIterator<models.schemas.UploadPart> {
    const options: ChunkedUploadsManagerListFileUploadSessionPartsOptions = { ...opts };
    for (;;) {
      const page = await this.listFileUploadSessionPartsPage(uploadSessionId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listFileUploadSessionPartsPage(uploadSessionId: string, opts?: ChunkedUploadsManagerListFileUploadSessionPartsOptions): Promise<models.schemas.UploadParts> {
    let url = this.session.baseUrl("upload_session");
    url += "/files";
    url += "/upload_sessions";
    url += '/' + pathEscape(uploadSessionId);
    url += "/parts";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UploadParts;
  }

  async commitFileUploadSession(uploadSessionId: string, digest: string, body: models.schemas.FileUploadSessionCommitRequest, opts?: ChunkedUploadsManagerCommitFileUploadSessionOptions): Promise<models.schemas.Files> {
    let url = this.session.baseUrl("upload_session");
    url += "/files";
    url += "/upload_sessions";
    url += '/' + pathEscape(uploadSessionId);
    url += "/commit";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "digest", digest);
    const options = opts ?? {};
    if (options["if-match"] !== undefined) {
      req = runtime.withHeader(req, "if-match", options["if-match"]);
    }
    if (options["if-none-match"] !== undefined) {
      req = runtime.withHeader(req, "if-none-match", options["if-none-match"]);
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Files;
  }
}
