// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Operations for the "classifications" API area. */
export class ClassificationsManager {
  constructor(private readonly session: runtime.Client) {}

  async get(): Promise<models.schemas.ClassificationTemplate> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += "/enterprise";
    url += "/securityClassification-6VMVochwUWo";
    url += "/schema";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ClassificationTemplate;
  }

  async updateAdd(body: Array<models.schemas.ClassificationUpdateRequest>): Promise<models.schemas.ClassificationTemplate> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += "/enterprise";
    url += "/securityClassification-6VMVochwUWo";
    url += "/schema";
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ClassificationTemplate;
  }

  async updateUpdate(body: Array<models.schemas.ClassificationUpdateRequest2>): Promise<models.schemas.ClassificationTemplate> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += "/enterprise";
    url += "/securityClassification-6VMVochwUWo";
    url += "/schema";
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ClassificationTemplate;
  }

  async createMetadataTemplateSchemaClassifications(body: models.schemas.MetadataTemplateSchemaCreateRequest): Promise<models.schemas.ClassificationTemplate> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += "/schema";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ClassificationTemplate;
  }
}
