// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for CollectionsManager.list. */
export interface CollectionsManagerListOptions {
  fields?: Array<string>;
  offset?: number;
  limit?: number;
}

/** Optional parameters for CollectionsManager.listItems. */
export interface CollectionsManagerListItemsOptions {
  fields?: Array<string>;
  offset?: number;
  limit?: number;
}

/** Operations for the "collections" API area. */
export class CollectionsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.Collection` across pages, threading the offset cursor. */
  async *list(opts?: CollectionsManagerListOptions): AsyncIterableIterator<models.schemas.Collection> {
    const options: CollectionsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listPage(opts?: CollectionsManagerListOptions): Promise<models.schemas.Collections> {
    let url = this.session.baseUrl("api");
    url += "/collections";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Collections;
  }

  /** Iterate every `models.schemas.Item` across pages, threading the offset cursor. */
  async *listItems(collectionId: string, opts?: CollectionsManagerListItemsOptions): AsyncIterableIterator<models.schemas.Item> {
    const options: CollectionsManagerListItemsOptions = { ...opts };
    for (;;) {
      const page = await this.listItemsPage(collectionId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listItemsPage(collectionId: string, opts?: CollectionsManagerListItemsOptions): Promise<models.schemas.ItemsOffsetPaginated> {
    let url = this.session.baseUrl("api");
    url += "/collections";
    url += '/' + pathEscape(collectionId);
    url += "/items";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ItemsOffsetPaginated;
  }

  async get(collectionId: string): Promise<models.schemas.Collection> {
    let url = this.session.baseUrl("api");
    url += "/collections";
    url += '/' + pathEscape(collectionId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Collection;
  }
}
