// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for CollaborationAllowlistEntriesManager.listCollaborationWhitelistEntries. */
export interface CollaborationAllowlistEntriesManagerListCollaborationWhitelistEntriesOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "collaboration_allowlist_entries" API area. */
export class CollaborationAllowlistEntriesManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.CollaborationAllowlistEntry` across pages, threading the marker cursor. */
  async *listCollaborationWhitelistEntries(opts?: CollaborationAllowlistEntriesManagerListCollaborationWhitelistEntriesOptions): AsyncIterableIterator<models.schemas.CollaborationAllowlistEntry> {
    const options: CollaborationAllowlistEntriesManagerListCollaborationWhitelistEntriesOptions = { ...opts };
    for (;;) {
      const page = await this.listCollaborationWhitelistEntriesPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listCollaborationWhitelistEntriesPage(opts?: CollaborationAllowlistEntriesManagerListCollaborationWhitelistEntriesOptions): Promise<models.schemas.CollaborationAllowlistEntries> {
    let url = this.session.baseUrl("api");
    url += "/collaboration_whitelist_entries";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CollaborationAllowlistEntries;
  }

  async createCollaborationWhitelistEntries(body: models.schemas.CollaborationWhitelistEntriesCreateRequest): Promise<models.schemas.CollaborationAllowlistEntry> {
    let url = this.session.baseUrl("api");
    url += "/collaboration_whitelist_entries";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CollaborationAllowlistEntry;
  }

  async getCollaborationWhitelistEntry(collaborationWhitelistEntryId: string): Promise<models.schemas.CollaborationAllowlistEntry> {
    let url = this.session.baseUrl("api");
    url += "/collaboration_whitelist_entries";
    url += '/' + pathEscape(collaborationWhitelistEntryId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CollaborationAllowlistEntry;
  }

  async deleteCollaborationWhitelistEntry(collaborationWhitelistEntryId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/collaboration_whitelist_entries";
    url += '/' + pathEscape(collaborationWhitelistEntryId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
