// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for CollaborationAllowlistExemptTargetsManager.listCollaborationWhitelistExemptTargets. */
export interface CollaborationAllowlistExemptTargetsManagerListCollaborationWhitelistExemptTargetsOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "collaboration_allowlist_exempt_targets" API area. */
export class CollaborationAllowlistExemptTargetsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.CollaborationAllowlistExemptTarget` across pages, threading the marker cursor. */
  async *listCollaborationWhitelistExemptTargets(opts?: CollaborationAllowlistExemptTargetsManagerListCollaborationWhitelistExemptTargetsOptions): AsyncIterableIterator<models.schemas.CollaborationAllowlistExemptTarget> {
    const options: CollaborationAllowlistExemptTargetsManagerListCollaborationWhitelistExemptTargetsOptions = { ...opts };
    for (;;) {
      const page = await this.listCollaborationWhitelistExemptTargetsPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listCollaborationWhitelistExemptTargetsPage(opts?: CollaborationAllowlistExemptTargetsManagerListCollaborationWhitelistExemptTargetsOptions): Promise<models.schemas.CollaborationAllowlistExemptTargets> {
    let url = this.session.baseUrl("api");
    url += "/collaboration_whitelist_exempt_targets";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CollaborationAllowlistExemptTargets;
  }

  async createCollaborationWhitelistExemptTargets(body: models.schemas.CollaborationWhitelistExemptTargetsCreateRequest): Promise<models.schemas.CollaborationAllowlistExemptTarget> {
    let url = this.session.baseUrl("api");
    url += "/collaboration_whitelist_exempt_targets";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CollaborationAllowlistExemptTarget;
  }

  async getCollaborationWhitelistExemptTarget(collaborationWhitelistExemptTargetId: string): Promise<models.schemas.CollaborationAllowlistExemptTarget> {
    let url = this.session.baseUrl("api");
    url += "/collaboration_whitelist_exempt_targets";
    url += '/' + pathEscape(collaborationWhitelistExemptTargetId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CollaborationAllowlistExemptTarget;
  }

  async deleteCollaborationWhitelistExemptTarget(collaborationWhitelistExemptTargetId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/collaboration_whitelist_exempt_targets";
    url += '/' + pathEscape(collaborationWhitelistExemptTargetId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
