// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for CommentsManager.listFile. */
export interface CommentsManagerListFileOptions {
  fields?: Array<string>;
  limit?: number;
  offset?: number;
}

/** Optional parameters for CommentsManager.get. */
export interface CommentsManagerGetOptions {
  fields?: Array<string>;
}

/** Optional parameters for CommentsManager.update. */
export interface CommentsManagerUpdateOptions {
  fields?: Array<string>;
}

/** Optional parameters for CommentsManager.create. */
export interface CommentsManagerCreateOptions {
  fields?: Array<string>;
}

/** Operations for the "comments" API area. */
export class CommentsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.CommentFull` across pages, threading the offset cursor. */
  async *listFile(fileId: string, opts?: CommentsManagerListFileOptions): AsyncIterableIterator<models.schemas.CommentFull> {
    const options: CommentsManagerListFileOptions = { ...opts };
    for (;;) {
      const page = await this.listFilePage(fileId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listFilePage(fileId: string, opts?: CommentsManagerListFileOptions): Promise<models.schemas.Comments> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/comments";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Comments;
  }

  async get(commentId: string, opts?: CommentsManagerGetOptions): Promise<models.schemas.CommentFull> {
    let url = this.session.baseUrl("api");
    url += "/comments";
    url += '/' + pathEscape(commentId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CommentFull;
  }

  async update(commentId: string, body: models.schemas.CommentUpdateRequest, opts?: CommentsManagerUpdateOptions): Promise<models.schemas.CommentFull> {
    let url = this.session.baseUrl("api");
    url += "/comments";
    url += '/' + pathEscape(commentId);
    let req = this.session.newRequest("PUT", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CommentFull;
  }

  async delete_(commentId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/comments";
    url += '/' + pathEscape(commentId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  async create(body: models.schemas.CommentCreateRequest, opts?: CommentsManagerCreateOptions): Promise<models.schemas.CommentFull> {
    let url = this.session.baseUrl("api");
    url += "/comments";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CommentFull;
  }
}
