// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for DevicePinnersManager.listEnterprise. */
export interface DevicePinnersManagerListEnterpriseOptions {
  marker?: string;
  limit?: number;
  direction?: models.schemas.OrderDirection;
}

/** Operations for the "device_pinners" API area. */
export class DevicePinnersManager {
  constructor(private readonly session: runtime.Client) {}

  async get(devicePinnerId: string): Promise<models.schemas.DevicePinner> {
    let url = this.session.baseUrl("api");
    url += "/device_pinners";
    url += '/' + pathEscape(devicePinnerId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DevicePinner;
  }

  async delete_(devicePinnerId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/device_pinners";
    url += '/' + pathEscape(devicePinnerId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  /** Iterate every `models.schemas.DevicePinner` across pages, threading the marker cursor. */
  async *listEnterprise(enterpriseId: string, opts?: DevicePinnersManagerListEnterpriseOptions): AsyncIterableIterator<models.schemas.DevicePinner> {
    const options: DevicePinnersManagerListEnterpriseOptions = { ...opts };
    for (;;) {
      const page = await this.listEnterprisePage(enterpriseId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null) {
        return;
      }
      options.marker = String(cursor);
    }
  }

  private async listEnterprisePage(enterpriseId: string, opts?: DevicePinnersManagerListEnterpriseOptions): Promise<models.schemas.DevicePinners> {
    let url = this.session.baseUrl("api");
    url += "/enterprises";
    url += '/' + pathEscape(enterpriseId);
    url += "/device_pinners";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.direction !== undefined) {
      req = runtime.withQuery(req, "direction", options.direction);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DevicePinners;
  }
}
