// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for DocgenManager.listJobs. */
export interface DocgenManagerListJobsOptions {
  marker?: string;
  limit?: number;
}

/** Optional parameters for DocgenManager.listBatchJob. */
export interface DocgenManagerListBatchJobOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "docgen" API area. */
export class DocgenManager {
  constructor(private readonly session: runtime.Client) {}

  async getJob(jobId: string): Promise<models.schemas.DocGenJob> {
    let url = this.session.baseUrl("api");
    url += "/docgen_jobs";
    url += '/' + pathEscape(jobId);
    let req = this.session.newRequest("GET", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenJob;
  }

  /** Iterate every `models.schemas.DocGenJobFull` across pages, threading the marker cursor. */
  async *listJobs(opts?: DocgenManagerListJobsOptions): AsyncIterableIterator<models.schemas.DocGenJobFull> {
    const options: DocgenManagerListJobsOptions = { ...opts };
    for (;;) {
      const page = await this.listJobsPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listJobsPage(opts?: DocgenManagerListJobsOptions): Promise<models.schemas.DocGenJobsFull> {
    let url = this.session.baseUrl("api");
    url += "/docgen_jobs";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenJobsFull;
  }

  /** Iterate every `models.schemas.DocGenJob` across pages, threading the marker cursor. */
  async *listBatchJob(batchId: string, opts?: DocgenManagerListBatchJobOptions): AsyncIterableIterator<models.schemas.DocGenJob> {
    const options: DocgenManagerListBatchJobOptions = { ...opts };
    for (;;) {
      const page = await this.listBatchJobPage(batchId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listBatchJobPage(batchId: string, opts?: DocgenManagerListBatchJobOptions): Promise<models.schemas.DocGenJobs> {
    let url = this.session.baseUrl("api");
    url += "/docgen_batch_jobs";
    url += '/' + pathEscape(batchId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenJobs;
  }

  async createBatches(body: models.schemas.DocGenBatchCreateRequest): Promise<models.schemas.DocGenBatchBase> {
    let url = this.session.baseUrl("api");
    url += "/docgen_batches";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenBatchBase;
  }
}
