// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for DocgenTemplateManager.listDocgenTemplates. */
export interface DocgenTemplateManagerListDocgenTemplatesOptions {
  marker?: string;
  limit?: number;
}

/** Optional parameters for DocgenTemplateManager.listDocgenTemplateTags. */
export interface DocgenTemplateManagerListDocgenTemplateTagsOptions {
  template_version_id?: string;
  marker?: string;
  limit?: number;
}

/** Optional parameters for DocgenTemplateManager.listJob. */
export interface DocgenTemplateManagerListJobOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "docgen_template" API area. */
export class DocgenTemplateManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.DocGenTemplate` across pages, threading the marker cursor. */
  async *listDocgenTemplates(opts?: DocgenTemplateManagerListDocgenTemplatesOptions): AsyncIterableIterator<models.schemas.DocGenTemplate> {
    const options: DocgenTemplateManagerListDocgenTemplatesOptions = { ...opts };
    for (;;) {
      const page = await this.listDocgenTemplatesPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listDocgenTemplatesPage(opts?: DocgenTemplateManagerListDocgenTemplatesOptions): Promise<models.schemas.DocGenTemplates> {
    let url = this.session.baseUrl("api");
    url += "/docgen_templates";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenTemplates;
  }

  async createDocgenTemplates(body: models.schemas.DocGenTemplateCreateRequest): Promise<models.schemas.DocGenTemplateBase> {
    let url = this.session.baseUrl("api");
    url += "/docgen_templates";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenTemplateBase;
  }

  async getDocgenTemplate(templateId: string): Promise<models.schemas.DocGenTemplate> {
    let url = this.session.baseUrl("api");
    url += "/docgen_templates";
    url += '/' + pathEscape(templateId);
    let req = this.session.newRequest("GET", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenTemplate;
  }

  async deleteDocgenTemplate(templateId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/docgen_templates";
    url += '/' + pathEscape(templateId);
    let req = this.session.newRequest("DELETE", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    await this.session.fetch(req);
  }

  /** Iterate every `models.schemas.DocGenTag` across pages, threading the marker cursor. */
  async *listDocgenTemplateTags(templateId: string, opts?: DocgenTemplateManagerListDocgenTemplateTagsOptions): AsyncIterableIterator<models.schemas.DocGenTag> {
    const options: DocgenTemplateManagerListDocgenTemplateTagsOptions = { ...opts };
    for (;;) {
      const page = await this.listDocgenTemplateTagsPage(templateId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listDocgenTemplateTagsPage(templateId: string, opts?: DocgenTemplateManagerListDocgenTemplateTagsOptions): Promise<models.schemas.DocGenTags> {
    let url = this.session.baseUrl("api");
    url += "/docgen_templates";
    url += '/' + pathEscape(templateId);
    url += "/tags";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.template_version_id !== undefined) {
      req = runtime.withQuery(req, "template_version_id", options.template_version_id);
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenTags;
  }

  /** Iterate every `models.schemas.DocGenJob` across pages, threading the marker cursor. */
  async *listJob(templateId: string, opts?: DocgenTemplateManagerListJobOptions): AsyncIterableIterator<models.schemas.DocGenJob> {
    const options: DocgenTemplateManagerListJobOptions = { ...opts };
    for (;;) {
      const page = await this.listJobPage(templateId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listJobPage(templateId: string, opts?: DocgenTemplateManagerListJobOptions): Promise<models.schemas.DocGenJobs> {
    let url = this.session.baseUrl("api");
    url += "/docgen_template_jobs";
    url += '/' + pathEscape(templateId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.DocGenJobs;
  }
}
