// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for DownloadsManager.getFileContent. */
export interface DownloadsManagerGetFileContentOptions {
  range?: string;
  boxapi?: string;
  version?: string;
  access_token?: string;
}

/** Operations for the "downloads" API area. */
export class DownloadsManager {
  constructor(private readonly session: runtime.Client) {}

  async getFileContent(fileId: string, opts?: DownloadsManagerGetFileContentOptions): Promise<runtime.Stream> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/content";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.range !== undefined) {
      req = runtime.withHeader(req, "range", options.range);
    }
    if (options.boxapi !== undefined) {
      req = runtime.withHeader(req, "boxapi", options.boxapi);
    }
    if (options.version !== undefined) {
      req = runtime.withQuery(req, "version", options.version);
    }
    if (options.access_token !== undefined) {
      req = runtime.withQuery(req, "access_token", options.access_token);
    }
    const resp = await this.session.fetch(req);
    return runtime.responseStream(resp);
  }
}
