// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "email_aliases" API area. */
export class EmailAliasesManager {
  constructor(private readonly session: runtime.Client) {}

  async listUser(userId: string): Promise<models.schemas.EmailAliases> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    url += "/email_aliases";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.EmailAliases;
  }

  async createUser(userId: string, body: models.schemas.UserIdCreateRequest): Promise<models.schemas.EmailAlias> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    url += "/email_aliases";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.EmailAlias;
  }

  async deleteUser(userId: string, emailAliasId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    url += "/email_aliases";
    url += '/' + pathEscape(emailAliasId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
