// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "enterprise_configurations" API area. */
export class EnterpriseConfigurationsManager {
  constructor(private readonly session: runtime.Client) {}

  async get(enterpriseId: string, categories: Array<string>): Promise<models.schemas.EnterpriseConfiguration> {
    let url = this.session.baseUrl("api");
    url += "/enterprise_configurations";
    url += '/' + pathEscape(enterpriseId);
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "categories", categories.join(','));
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.EnterpriseConfiguration;
  }
}
