// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { join } from '../internal.js';

/** Optional parameters for EventsManager.list. */
export interface EventsManagerListOptions {
  stream_type?: models.schemas.GetStreamType;
  stream_position?: string;
  limit?: number;
  event_type?: Array<models.schemas.GetEventType>;
  created_after?: string;
  created_before?: string;
}

/** Operations for the "events" API area. */
export class EventsManager {
  constructor(private readonly session: runtime.Client) {}

  async list(opts?: EventsManagerListOptions): Promise<models.schemas.Events> {
    let url = this.session.baseUrl("api");
    url += "/events";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.stream_type !== undefined) {
      req = runtime.withQuery(req, "stream_type", options.stream_type);
    }
    if (options.stream_position !== undefined) {
      req = runtime.withQuery(req, "stream_position", options.stream_position);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.event_type !== undefined) {
      req = runtime.withQuery(req, "event_type", join(options.event_type, (v) => v));
    }
    if (options.created_after !== undefined) {
      req = runtime.withQuery(req, "created_after", options.created_after);
    }
    if (options.created_before !== undefined) {
      req = runtime.withQuery(req, "created_before", options.created_before);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Events;
  }

  async options(): Promise<models.schemas.RealtimeServers> {
    let url = this.session.baseUrl("api");
    url += "/events";
    let req = this.session.newRequest("OPTIONS", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RealtimeServers;
  }
}
