// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Operations for the "external_users" API area. */
export class ExternalUsersManager {
  constructor(private readonly session: runtime.Client) {}

  async createSubmitDeleteJob(body: models.schemas.ExternalUsersSubmitDeleteJobRequest): Promise<models.schemas.ExternalUsersSubmitDeleteJobResponse> {
    let url = this.session.baseUrl("api");
    url += "/external_users";
    url += "/submit_delete_job";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ExternalUsersSubmitDeleteJobResponse;
  }
}
