// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for FilesManager.get. */
export interface FilesManagerGetOptions {
  fields?: Array<string>;
  "if-none-match"?: string;
  boxapi?: string;
  "x-rep-hints"?: string;
}

/** Optional parameters for FilesManager.update. */
export interface FilesManagerUpdateOptions {
  fields?: Array<string>;
  "if-match"?: string;
}

/** Optional parameters for FilesManager.delete_. */
export interface FilesManagerDeleteOptions {
  "if-match"?: string;
}

/** Optional parameters for FilesManager.copy. */
export interface FilesManagerCopyOptions {
  fields?: Array<string>;
}

/** Optional parameters for FilesManager.getThumbnail. */
export interface FilesManagerGetThumbnailOptions {
  min_height?: number;
  min_width?: number;
  max_height?: number;
  max_width?: number;
}

/** Operations for the "files" API area. */
export class FilesManager {
  constructor(private readonly session: runtime.Client) {}

  async get(fileId: string, opts?: FilesManagerGetOptions): Promise<models.schemas.FileFull> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options["if-none-match"] !== undefined) {
      req = runtime.withHeader(req, "if-none-match", options["if-none-match"]);
    }
    if (options.boxapi !== undefined) {
      req = runtime.withHeader(req, "boxapi", options.boxapi);
    }
    if (options["x-rep-hints"] !== undefined) {
      req = runtime.withHeader(req, "x-rep-hints", options["x-rep-hints"]);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileFull;
  }

  async update(fileId: string, body: models.schemas.FileUpdateRequest, opts?: FilesManagerUpdateOptions): Promise<models.schemas.FileFull> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    let req = this.session.newRequest("PUT", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options["if-match"] !== undefined) {
      req = runtime.withHeader(req, "if-match", options["if-match"]);
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileFull;
  }

  async delete_(fileId: string, opts?: FilesManagerDeleteOptions): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    let req = this.session.newRequest("DELETE", url);
    const options = opts ?? {};
    if (options["if-match"] !== undefined) {
      req = runtime.withHeader(req, "if-match", options["if-match"]);
    }
    await this.session.fetch(req);
  }

  async copy(fileId: string, body: models.schemas.FileCopyRequest, opts?: FilesManagerCopyOptions): Promise<models.schemas.FileFull> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/copy";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileFull;
  }

  async getThumbnail(fileId: string, extension: models.schemas.GetIdThumbnailIdExtension, opts?: FilesManagerGetThumbnailOptions): Promise<runtime.Stream> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += '/';
    url += "thumbnail.";
    url += pathEscape(extension);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.min_height !== undefined) {
      req = runtime.withQuery(req, "min_height", String(options.min_height));
    }
    if (options.min_width !== undefined) {
      req = runtime.withQuery(req, "min_width", String(options.min_width));
    }
    if (options.max_height !== undefined) {
      req = runtime.withQuery(req, "max_height", String(options.max_height));
    }
    if (options.max_width !== undefined) {
      req = runtime.withQuery(req, "max_width", String(options.max_width));
    }
    const resp = await this.session.fetch(req);
    return runtime.responseStream(resp);
  }
}
