// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for FileVersionRetentionsManager.list. */
export interface FileVersionRetentionsManagerListOptions {
  file_id?: string;
  file_version_id?: string;
  policy_id?: string;
  disposition_action?: models.schemas.RetentionPolicyDispositionAction;
  disposition_before?: string;
  disposition_after?: string;
  limit?: number;
  marker?: string;
}

/** Operations for the "file_version_retentions" API area. */
export class FileVersionRetentionsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.FileVersionRetention` across pages, threading the marker cursor. */
  async *list(opts?: FileVersionRetentionsManagerListOptions): AsyncIterableIterator<models.schemas.FileVersionRetention> {
    const options: FileVersionRetentionsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: FileVersionRetentionsManagerListOptions): Promise<models.schemas.FileVersionRetentions> {
    let url = this.session.baseUrl("api");
    url += "/file_version_retentions";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.file_id !== undefined) {
      req = runtime.withQuery(req, "file_id", options.file_id);
    }
    if (options.file_version_id !== undefined) {
      req = runtime.withQuery(req, "file_version_id", options.file_version_id);
    }
    if (options.policy_id !== undefined) {
      req = runtime.withQuery(req, "policy_id", options.policy_id);
    }
    if (options.disposition_action !== undefined) {
      req = runtime.withQuery(req, "disposition_action", options.disposition_action);
    }
    if (options.disposition_before !== undefined) {
      req = runtime.withQuery(req, "disposition_before", options.disposition_before);
    }
    if (options.disposition_after !== undefined) {
      req = runtime.withQuery(req, "disposition_after", options.disposition_after);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersionRetentions;
  }

  async get(fileVersionRetentionId: string): Promise<models.schemas.FileVersionRetention> {
    let url = this.session.baseUrl("api");
    url += "/file_version_retentions";
    url += '/' + pathEscape(fileVersionRetentionId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersionRetention;
  }
}
