// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for FileVersionsManager.listFileVersions. */
export interface FileVersionsManagerListFileVersionsOptions {
  fields?: Array<string>;
  limit?: number;
  offset?: number;
}

/** Optional parameters for FileVersionsManager.getFileVersion. */
export interface FileVersionsManagerGetFileVersionOptions {
  fields?: Array<string>;
}

/** Optional parameters for FileVersionsManager.deleteFileVersion. */
export interface FileVersionsManagerDeleteFileVersionOptions {
  "if-match"?: string;
}

/** Optional parameters for FileVersionsManager.createFileVersionCurrent. */
export interface FileVersionsManagerCreateFileVersionCurrentOptions {
  fields?: Array<string>;
}

/** Operations for the "file_versions" API area. */
export class FileVersionsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.FileVersionFull` across pages, threading the offset cursor. */
  async *listFileVersions(fileId: string, opts?: FileVersionsManagerListFileVersionsOptions): AsyncIterableIterator<models.schemas.FileVersionFull> {
    const options: FileVersionsManagerListFileVersionsOptions = { ...opts };
    for (;;) {
      const page = await this.listFileVersionsPage(fileId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listFileVersionsPage(fileId: string, opts?: FileVersionsManagerListFileVersionsOptions): Promise<models.schemas.FileVersions> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/versions";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersions;
  }

  async getFileVersion(fileId: string, fileVersionId: string, opts?: FileVersionsManagerGetFileVersionOptions): Promise<models.schemas.FileVersionFull> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/versions";
    url += '/' + pathEscape(fileVersionId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersionFull;
  }

  async updateFileVersion(fileId: string, fileVersionId: string, body: models.schemas.FileVersionUpdateRequest): Promise<models.schemas.FileVersionFull> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/versions";
    url += '/' + pathEscape(fileVersionId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersionFull;
  }

  async deleteFileVersion(fileId: string, fileVersionId: string, opts?: FileVersionsManagerDeleteFileVersionOptions): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/versions";
    url += '/' + pathEscape(fileVersionId);
    let req = this.session.newRequest("DELETE", url);
    const options = opts ?? {};
    if (options["if-match"] !== undefined) {
      req = runtime.withHeader(req, "if-match", options["if-match"]);
    }
    await this.session.fetch(req);
  }

  async createFileVersionCurrent(fileId: string, body: models.schemas.FileVersionCurrentCreateRequest, opts?: FileVersionsManagerCreateFileVersionCurrentOptions): Promise<models.schemas.FileVersionFull> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/versions";
    url += "/current";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersionFull;
  }
}
