// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for FileVersionLegalHoldsManager.list. */
export interface FileVersionLegalHoldsManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "file_version_legal_holds" API area. */
export class FileVersionLegalHoldsManager {
  constructor(private readonly session: runtime.Client) {}

  async get(fileVersionLegalHoldId: string): Promise<models.schemas.FileVersionLegalHold> {
    let url = this.session.baseUrl("api");
    url += "/file_version_legal_holds";
    url += '/' + pathEscape(fileVersionLegalHoldId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersionLegalHold;
  }

  /** Iterate every `models.schemas.FileVersionLegalHold` across pages, threading the marker cursor. */
  async *list(policyId: string, opts?: FileVersionLegalHoldsManagerListOptions): AsyncIterableIterator<models.schemas.FileVersionLegalHold> {
    const options: FileVersionLegalHoldsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(policyId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(policyId: string, opts?: FileVersionLegalHoldsManagerListOptions): Promise<models.schemas.FileVersionLegalHolds> {
    let url = this.session.baseUrl("api");
    url += "/file_version_legal_holds";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "policy_id", policyId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersionLegalHolds;
  }
}
