// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for FileRequestsManager.update. */
export interface FileRequestsManagerUpdateOptions {
  "if-match"?: string;
}

/** Operations for the "file_requests" API area. */
export class FileRequestsManager {
  constructor(private readonly session: runtime.Client) {}

  async get(fileRequestId: string): Promise<models.schemas.FileRequest> {
    let url = this.session.baseUrl("api");
    url += "/file_requests";
    url += '/' + pathEscape(fileRequestId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileRequest;
  }

  async update(fileRequestId: string, body: models.schemas.FileRequestUpdateRequest, opts?: FileRequestsManagerUpdateOptions): Promise<models.schemas.FileRequest> {
    let url = this.session.baseUrl("api");
    url += "/file_requests";
    url += '/' + pathEscape(fileRequestId);
    let req = this.session.newRequest("PUT", url);
    const options = opts ?? {};
    if (options["if-match"] !== undefined) {
      req = runtime.withHeader(req, "if-match", options["if-match"]);
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileRequest;
  }

  async delete_(fileRequestId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/file_requests";
    url += '/' + pathEscape(fileRequestId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  async copy(fileRequestId: string, body: models.schemas.FileRequestCopyRequest): Promise<models.schemas.FileRequest> {
    let url = this.session.baseUrl("api");
    url += "/file_requests";
    url += '/' + pathEscape(fileRequestId);
    url += "/copy";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileRequest;
  }
}
