// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "folder_watermarks" API area. */
export class FolderWatermarksManager {
  constructor(private readonly session: runtime.Client) {}

  async getFolderWatermark(folderId: string): Promise<models.schemas.Watermark> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/watermark";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Watermark;
  }

  async updateFolderWatermark(folderId: string, body: models.schemas.FileWatermarkUpdateRequest): Promise<models.schemas.Watermark> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/watermark";
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Watermark;
  }

  async deleteFolderWatermark(folderId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/watermark";
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
