// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "folder_locks" API area. */
export class FolderLocksManager {
  constructor(private readonly session: runtime.Client) {}

  async list(folderId: string): Promise<models.schemas.FolderLocks> {
    let url = this.session.baseUrl("api");
    url += "/folder_locks";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "folder_id", folderId);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FolderLocks;
  }

  async create(body: models.schemas.FolderLockCreateRequest): Promise<models.schemas.FolderLock> {
    let url = this.session.baseUrl("api");
    url += "/folder_locks";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FolderLock;
  }

  async delete_(folderLockId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/folder_locks";
    url += '/' + pathEscape(folderLockId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
