// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for FoldersManager.get. */
export interface FoldersManagerGetOptions {
  fields?: Array<string>;
  "if-none-match"?: string;
  boxapi?: string;
  sort?: models.schemas.GetIdSort;
  direction?: models.schemas.OrderDirection;
  offset?: number;
  limit?: number;
}

/** Optional parameters for FoldersManager.update. */
export interface FoldersManagerUpdateOptions {
  fields?: Array<string>;
  "if-match"?: string;
}

/** Optional parameters for FoldersManager.delete_. */
export interface FoldersManagerDeleteOptions {
  "if-match"?: string;
  recursive?: boolean;
}

/** Optional parameters for FoldersManager.listItems. */
export interface FoldersManagerListItemsOptions {
  fields?: Array<string>;
  usemarker?: boolean;
  marker?: string;
  offset?: number;
  limit?: number;
  boxapi?: string;
  sort?: models.schemas.GetIdSort;
  direction?: models.schemas.OrderDirection;
}

/** Optional parameters for FoldersManager.create. */
export interface FoldersManagerCreateOptions {
  fields?: Array<string>;
}

/** Optional parameters for FoldersManager.copy. */
export interface FoldersManagerCopyOptions {
  fields?: Array<string>;
}

/** Operations for the "folders" API area. */
export class FoldersManager {
  constructor(private readonly session: runtime.Client) {}

  async get(folderId: string, opts?: FoldersManagerGetOptions): Promise<models.schemas.FolderFull> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options["if-none-match"] !== undefined) {
      req = runtime.withHeader(req, "if-none-match", options["if-none-match"]);
    }
    if (options.boxapi !== undefined) {
      req = runtime.withHeader(req, "boxapi", options.boxapi);
    }
    if (options.sort !== undefined) {
      req = runtime.withQuery(req, "sort", options.sort);
    }
    if (options.direction !== undefined) {
      req = runtime.withQuery(req, "direction", options.direction);
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FolderFull;
  }

  async update(folderId: string, body: models.schemas.FolderUpdateRequest, opts?: FoldersManagerUpdateOptions): Promise<models.schemas.FolderFull> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    let req = this.session.newRequest("PUT", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options["if-match"] !== undefined) {
      req = runtime.withHeader(req, "if-match", options["if-match"]);
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FolderFull;
  }

  async delete_(folderId: string, opts?: FoldersManagerDeleteOptions): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    let req = this.session.newRequest("DELETE", url);
    const options = opts ?? {};
    if (options["if-match"] !== undefined) {
      req = runtime.withHeader(req, "if-match", options["if-match"]);
    }
    if (options.recursive !== undefined) {
      req = runtime.withQuery(req, "recursive", String(options.recursive));
    }
    await this.session.fetch(req);
  }

  /** Iterate every `models.schemas.Item` across pages, threading the marker cursor. */
  async *listItems(folderId: string, opts?: FoldersManagerListItemsOptions): AsyncIterableIterator<models.schemas.Item> {
    const options: FoldersManagerListItemsOptions = { ...opts };
    for (;;) {
      const page = await this.listItemsPage(folderId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listItemsPage(folderId: string, opts?: FoldersManagerListItemsOptions): Promise<models.schemas.Items> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/items";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.usemarker !== undefined) {
      req = runtime.withQuery(req, "usemarker", String(options.usemarker));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.boxapi !== undefined) {
      req = runtime.withHeader(req, "boxapi", options.boxapi);
    }
    if (options.sort !== undefined) {
      req = runtime.withQuery(req, "sort", options.sort);
    }
    if (options.direction !== undefined) {
      req = runtime.withQuery(req, "direction", options.direction);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Items;
  }

  async create(body: models.schemas.FolderCreateRequest, opts?: FoldersManagerCreateOptions): Promise<models.schemas.FolderFull> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FolderFull;
  }

  async copy(folderId: string, body: models.schemas.FolderCopyRequest, opts?: FoldersManagerCopyOptions): Promise<models.schemas.FolderFull> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/copy";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FolderFull;
  }
}
