// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "folder_classifications" API area. */
export class FolderClassificationsManager {
  constructor(private readonly session: runtime.Client) {}

  async get(folderId: string): Promise<models.schemas.Classification> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    url += "/enterprise";
    url += "/securityClassification-6VMVochwUWo";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Classification;
  }

  async update(folderId: string, body: Array<models.schemas.FileClassificationUpdateRequest>): Promise<models.schemas.Classification> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    url += "/enterprise";
    url += "/securityClassification-6VMVochwUWo";
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Classification;
  }

  async create(folderId: string, body: models.schemas.FileClassificationCreateRequest): Promise<models.schemas.Classification> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    url += "/enterprise";
    url += "/securityClassification-6VMVochwUWo";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Classification;
  }

  async delete_(folderId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    url += "/enterprise";
    url += "/securityClassification-6VMVochwUWo";
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
