// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for FolderMetadataManager.listFolderMetadata. */
export interface FolderMetadataManagerListFolderMetadataOptions {
  view?: string;
}

/** Operations for the "folder_metadata" API area. */
export class FolderMetadataManager {
  constructor(private readonly session: runtime.Client) {}

  async listFolderMetadata(folderId: string, opts?: FolderMetadataManagerListFolderMetadataOptions): Promise<models.schemas.Metadatas> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.view !== undefined) {
      req = runtime.withQuery(req, "view", options.view);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Metadatas;
  }

  async getFolderMetadata(folderId: string, scope: models.schemas.GetFileIdMetadataIdIdScope, templateKey: string): Promise<models.schemas.MetadataFull> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    url += '/' + pathEscape(scope);
    url += '/' + pathEscape(templateKey);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataFull;
  }

  async updateFolderMetadata(folderId: string, scope: models.schemas.GetFileIdMetadataIdIdScope, templateKey: string, body: Array<models.schemas.FileMetadataUpdateRequest>): Promise<models.schemas.MetadataFull> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    url += '/' + pathEscape(scope);
    url += '/' + pathEscape(templateKey);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataFull;
  }

  async createFolderMetadata(folderId: string, scope: models.schemas.GetFileIdMetadataIdIdScope, templateKey: string, body: Record<string, unknown>): Promise<models.schemas.MetadataFull> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    url += '/' + pathEscape(scope);
    url += '/' + pathEscape(templateKey);
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataFull;
  }

  async deleteFolderMetadata(folderId: string, scope: models.schemas.GetFileIdMetadataIdIdScope, templateKey: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/metadata";
    url += '/' + pathEscape(scope);
    url += '/' + pathEscape(templateKey);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
