// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for GroupsManager.list. */
export interface GroupsManagerListOptions {
  filter_term?: string;
  fields?: Array<string>;
  limit?: number;
  offset?: number;
}

/** Optional parameters for GroupsManager.create. */
export interface GroupsManagerCreateOptions {
  fields?: Array<string>;
}

/** Optional parameters for GroupsManager.get. */
export interface GroupsManagerGetOptions {
  fields?: Array<string>;
}

/** Optional parameters for GroupsManager.update. */
export interface GroupsManagerUpdateOptions {
  fields?: Array<string>;
}

/** Operations for the "groups" API area. */
export class GroupsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.GroupFull` across pages, threading the offset cursor. */
  async *list(opts?: GroupsManagerListOptions): AsyncIterableIterator<models.schemas.GroupFull> {
    const options: GroupsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listPage(opts?: GroupsManagerListOptions): Promise<models.schemas.Groups> {
    let url = this.session.baseUrl("api");
    url += "/groups";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.filter_term !== undefined) {
      req = runtime.withQuery(req, "filter_term", options.filter_term);
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Groups;
  }

  async create(body: models.schemas.GroupCreateRequest, opts?: GroupsManagerCreateOptions): Promise<models.schemas.GroupFull> {
    let url = this.session.baseUrl("api");
    url += "/groups";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.GroupFull;
  }

  async get(groupId: string, opts?: GroupsManagerGetOptions): Promise<models.schemas.GroupFull> {
    let url = this.session.baseUrl("api");
    url += "/groups";
    url += '/' + pathEscape(groupId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.GroupFull;
  }

  async update(groupId: string, body: models.schemas.GroupUpdateRequest, opts?: GroupsManagerUpdateOptions): Promise<models.schemas.GroupFull> {
    let url = this.session.baseUrl("api");
    url += "/groups";
    url += '/' + pathEscape(groupId);
    let req = this.session.newRequest("PUT", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.GroupFull;
  }

  async delete_(groupId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/groups";
    url += '/' + pathEscape(groupId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
