// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Optional parameters for HubDocumentManager.listPages. */
export interface HubDocumentManagerListPagesOptions {
  marker?: string;
  limit?: number;
}

/** Optional parameters for HubDocumentManager.listBlocks. */
export interface HubDocumentManagerListBlocksOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "hub_document" API area. */
export class HubDocumentManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.HubDocumentPage` across pages, threading the marker cursor. */
  async *listPages(hubId: string, opts?: HubDocumentManagerListPagesOptions): AsyncIterableIterator<models.schemas.HubDocumentPage> {
    const options: HubDocumentManagerListPagesOptions = { ...opts };
    for (;;) {
      const page = await this.listPagesPage(hubId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPagesPage(hubId: string, opts?: HubDocumentManagerListPagesOptions): Promise<models.schemas.HubDocumentPages> {
    let url = this.session.baseUrl("api");
    url += "/hub_document_pages";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "hub_id", hubId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.HubDocumentPages;
  }

  /** Iterate every `models.schemas.HubDocumentBlockEntry` across pages, threading the marker cursor. */
  async *listBlocks(hubId: string, pageId: string, opts?: HubDocumentManagerListBlocksOptions): AsyncIterableIterator<models.schemas.HubDocumentBlockEntry> {
    const options: HubDocumentManagerListBlocksOptions = { ...opts };
    for (;;) {
      const page = await this.listBlocksPage(hubId, pageId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listBlocksPage(hubId: string, pageId: string, opts?: HubDocumentManagerListBlocksOptions): Promise<models.schemas.HubDocumentBlocks> {
    let url = this.session.baseUrl("api");
    url += "/hub_document_blocks";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "hub_id", hubId);
    req = runtime.withQuery(req, "page_id", pageId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.HubDocumentBlocks;
  }
}
