// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for HubItemsManager.list. */
export interface HubItemsManagerListOptions {
  parent_id?: string;
  marker?: string;
  limit?: number;
}

/** Operations for the "hub_items" API area. */
export class HubItemsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.HubItem` across pages, threading the marker cursor. */
  async *list(hubId: string, opts?: HubItemsManagerListOptions): AsyncIterableIterator<models.schemas.HubItem> {
    const options: HubItemsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(hubId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(hubId: string, opts?: HubItemsManagerListOptions): Promise<models.schemas.HubItems> {
    let url = this.session.baseUrl("api");
    url += "/hub_items";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "hub_id", hubId);
    const options = opts ?? {};
    if (options.parent_id !== undefined) {
      req = runtime.withQuery(req, "parent_id", options.parent_id);
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.HubItems;
  }

  async createHubManageItems(hubId: string, body: models.schemas.HubItemsManageRequest): Promise<models.schemas.HubItemsManageResponse> {
    let url = this.session.baseUrl("api");
    url += "/hubs";
    url += '/' + pathEscape(hubId);
    url += "/manage_items";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.HubItemsManageResponse;
  }
}
