// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for HubCollaborationsManager.list. */
export interface HubCollaborationsManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "hub_collaborations" API area. */
export class HubCollaborationsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.HubCollaboration` across pages, threading the marker cursor. */
  async *list(hubId: string, opts?: HubCollaborationsManagerListOptions): AsyncIterableIterator<models.schemas.HubCollaboration> {
    const options: HubCollaborationsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(hubId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(hubId: string, opts?: HubCollaborationsManagerListOptions): Promise<models.schemas.HubCollaborations> {
    let url = this.session.baseUrl("api");
    url += "/hub_collaborations";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "hub_id", hubId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.HubCollaborations;
  }

  async create(body: models.schemas.HubCollaborationCreateRequest): Promise<models.schemas.HubCollaboration> {
    let url = this.session.baseUrl("api");
    url += "/hub_collaborations";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.HubCollaboration;
  }

  async get(hubCollaborationId: string): Promise<models.schemas.HubCollaboration> {
    let url = this.session.baseUrl("api");
    url += "/hub_collaborations";
    url += '/' + pathEscape(hubCollaborationId);
    let req = this.session.newRequest("GET", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.HubCollaboration;
  }

  async update(hubCollaborationId: string, body: models.schemas.HubCollaborationUpdateRequest): Promise<models.schemas.HubCollaboration> {
    let url = this.session.baseUrl("api");
    url += "/hub_collaborations";
    url += '/' + pathEscape(hubCollaborationId);
    let req = this.session.newRequest("PUT", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.HubCollaboration;
  }

  async delete_(hubCollaborationId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/hub_collaborations";
    url += '/' + pathEscape(hubCollaborationId);
    let req = this.session.newRequest("DELETE", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    await this.session.fetch(req);
  }
}
