// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for HubsManager.list. */
export interface HubsManagerListOptions {
  query?: string;
  scope?: string;
  sort?: string;
  direction?: models.schemas.GetDirection;
  marker?: string;
  limit?: number;
}

/** Optional parameters for HubsManager.listEnterprise. */
export interface HubsManagerListEnterpriseOptions {
  query?: string;
  sort?: string;
  direction?: models.schemas.GetDirection;
  marker?: string;
  limit?: number;
}

/** Operations for the "hubs" API area. */
export class HubsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.Hub` across pages, threading the marker cursor. */
  async *list(opts?: HubsManagerListOptions): AsyncIterableIterator<models.schemas.Hub> {
    const options: HubsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: HubsManagerListOptions): Promise<models.schemas.Hubs> {
    let url = this.session.baseUrl("api");
    url += "/hubs";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.query !== undefined) {
      req = runtime.withQuery(req, "query", options.query);
    }
    if (options.scope !== undefined) {
      req = runtime.withQuery(req, "scope", options.scope);
    }
    if (options.sort !== undefined) {
      req = runtime.withQuery(req, "sort", options.sort);
    }
    if (options.direction !== undefined) {
      req = runtime.withQuery(req, "direction", options.direction);
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Hubs;
  }

  async create(body: models.schemas.HubCreateRequest): Promise<models.schemas.Hub> {
    let url = this.session.baseUrl("api");
    url += "/hubs";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Hub;
  }

  /** Iterate every `models.schemas.Hub` across pages, threading the marker cursor. */
  async *listEnterprise(opts?: HubsManagerListEnterpriseOptions): AsyncIterableIterator<models.schemas.Hub> {
    const options: HubsManagerListEnterpriseOptions = { ...opts };
    for (;;) {
      const page = await this.listEnterprisePage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listEnterprisePage(opts?: HubsManagerListEnterpriseOptions): Promise<models.schemas.Hubs> {
    let url = this.session.baseUrl("api");
    url += "/enterprise_hubs";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.query !== undefined) {
      req = runtime.withQuery(req, "query", options.query);
    }
    if (options.sort !== undefined) {
      req = runtime.withQuery(req, "sort", options.sort);
    }
    if (options.direction !== undefined) {
      req = runtime.withQuery(req, "direction", options.direction);
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Hubs;
  }

  async get(hubId: string): Promise<models.schemas.Hub> {
    let url = this.session.baseUrl("api");
    url += "/hubs";
    url += '/' + pathEscape(hubId);
    let req = this.session.newRequest("GET", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Hub;
  }

  async update(hubId: string, body: models.schemas.HubUpdateRequest): Promise<models.schemas.Hub> {
    let url = this.session.baseUrl("api");
    url += "/hubs";
    url += '/' + pathEscape(hubId);
    let req = this.session.newRequest("PUT", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Hub;
  }

  async delete_(hubId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/hubs";
    url += '/' + pathEscape(hubId);
    let req = this.session.newRequest("DELETE", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    await this.session.fetch(req);
  }

  async copy(hubId: string, body: models.schemas.HubCopyRequest): Promise<models.schemas.Hub> {
    let url = this.session.baseUrl("api");
    url += "/hubs";
    url += '/' + pathEscape(hubId);
    url += "/copy";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Hub;
  }
}
