// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for IntegrationMappingsManager.listSlack. */
export interface IntegrationMappingsManagerListSlackOptions {
  marker?: string;
  limit?: number;
  partner_item_type?: models.schemas.IntegrationMappingPartnerItemSlackType;
  partner_item_id?: string;
  box_item_id?: string;
  box_item_type?: models.schemas.FolderType;
  is_manually_created?: boolean;
}

/** Optional parameters for IntegrationMappingsManager.listTeams. */
export interface IntegrationMappingsManagerListTeamsOptions {
  partner_item_type?: models.schemas.IntegrationMappingPartnerItemTeamsType;
  partner_item_id?: string;
  box_item_id?: string;
  box_item_type?: models.schemas.FolderType;
}

/** Operations for the "integration_mappings" API area. */
export class IntegrationMappingsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.IntegrationMapping` across pages, threading the marker cursor. */
  async *listSlack(opts?: IntegrationMappingsManagerListSlackOptions): AsyncIterableIterator<models.schemas.IntegrationMapping> {
    const options: IntegrationMappingsManagerListSlackOptions = { ...opts };
    for (;;) {
      const page = await this.listSlackPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listSlackPage(opts?: IntegrationMappingsManagerListSlackOptions): Promise<models.schemas.IntegrationMappings> {
    let url = this.session.baseUrl("api");
    url += "/integration_mappings";
    url += "/slack";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.partner_item_type !== undefined) {
      req = runtime.withQuery(req, "partner_item_type", options.partner_item_type);
    }
    if (options.partner_item_id !== undefined) {
      req = runtime.withQuery(req, "partner_item_id", options.partner_item_id);
    }
    if (options.box_item_id !== undefined) {
      req = runtime.withQuery(req, "box_item_id", options.box_item_id);
    }
    if (options.box_item_type !== undefined) {
      req = runtime.withQuery(req, "box_item_type", options.box_item_type);
    }
    if (options.is_manually_created !== undefined) {
      req = runtime.withQuery(req, "is_manually_created", String(options.is_manually_created));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.IntegrationMappings;
  }

  async createSlack(body: models.schemas.IntegrationMappingSlackCreateRequest): Promise<models.schemas.IntegrationMapping> {
    let url = this.session.baseUrl("api");
    url += "/integration_mappings";
    url += "/slack";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.IntegrationMapping;
  }

  async updateSlack(integrationMappingId: string, body: models.schemas.SlackUpdateRequest): Promise<models.schemas.IntegrationMapping> {
    let url = this.session.baseUrl("api");
    url += "/integration_mappings";
    url += "/slack";
    url += '/' + pathEscape(integrationMappingId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.IntegrationMapping;
  }

  async deleteSlack(integrationMappingId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/integration_mappings";
    url += "/slack";
    url += '/' + pathEscape(integrationMappingId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  async listTeams(opts?: IntegrationMappingsManagerListTeamsOptions): Promise<models.schemas.IntegrationMappingsTeams> {
    let url = this.session.baseUrl("api");
    url += "/integration_mappings";
    url += "/teams";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.partner_item_type !== undefined) {
      req = runtime.withQuery(req, "partner_item_type", options.partner_item_type);
    }
    if (options.partner_item_id !== undefined) {
      req = runtime.withQuery(req, "partner_item_id", options.partner_item_id);
    }
    if (options.box_item_id !== undefined) {
      req = runtime.withQuery(req, "box_item_id", options.box_item_id);
    }
    if (options.box_item_type !== undefined) {
      req = runtime.withQuery(req, "box_item_type", options.box_item_type);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.IntegrationMappingsTeams;
  }

  async createTeams(body: models.schemas.IntegrationMappingTeamsCreateRequest): Promise<models.schemas.IntegrationMappingTeams> {
    let url = this.session.baseUrl("api");
    url += "/integration_mappings";
    url += "/teams";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.IntegrationMappingTeams;
  }

  async updateTeam(integrationMappingId: string, body: models.schemas.TeamUpdateRequest): Promise<models.schemas.IntegrationMappingTeams> {
    let url = this.session.baseUrl("api");
    url += "/integration_mappings";
    url += "/teams";
    url += '/' + pathEscape(integrationMappingId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.IntegrationMappingTeams;
  }

  async deleteTeam(integrationMappingId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/integration_mappings";
    url += "/teams";
    url += '/' + pathEscape(integrationMappingId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
