// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for InvitesManager.create. */
export interface InvitesManagerCreateOptions {
  fields?: Array<string>;
}

/** Optional parameters for InvitesManager.get. */
export interface InvitesManagerGetOptions {
  fields?: Array<string>;
}

/** Operations for the "invites" API area. */
export class InvitesManager {
  constructor(private readonly session: runtime.Client) {}

  async create(body: models.schemas.InviteCreateRequest, opts?: InvitesManagerCreateOptions): Promise<models.schemas.Invite> {
    let url = this.session.baseUrl("api");
    url += "/invites";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Invite;
  }

  async get(inviteId: string, opts?: InvitesManagerGetOptions): Promise<models.schemas.Invite> {
    let url = this.session.baseUrl("api");
    url += "/invites";
    url += '/' + pathEscape(inviteId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Invite;
  }
}
