// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for LegalHoldPoliciesManager.list. */
export interface LegalHoldPoliciesManagerListOptions {
  policy_name?: string;
  fields?: Array<string>;
  marker?: string;
  limit?: number;
}

/** Operations for the "legal_hold_policies" API area. */
export class LegalHoldPoliciesManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.LegalHoldPolicy` across pages, threading the marker cursor. */
  async *list(opts?: LegalHoldPoliciesManagerListOptions): AsyncIterableIterator<models.schemas.LegalHoldPolicy> {
    const options: LegalHoldPoliciesManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: LegalHoldPoliciesManagerListOptions): Promise<models.schemas.LegalHoldPolicies> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policies";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.policy_name !== undefined) {
      req = runtime.withQuery(req, "policy_name", options.policy_name);
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.LegalHoldPolicies;
  }

  async create(body: models.schemas.LegalHoldPolicyCreateRequest): Promise<models.schemas.LegalHoldPolicy> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policies";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.LegalHoldPolicy;
  }

  async get(legalHoldPolicyId: string): Promise<models.schemas.LegalHoldPolicy> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policies";
    url += '/' + pathEscape(legalHoldPolicyId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.LegalHoldPolicy;
  }

  async update(legalHoldPolicyId: string, body: models.schemas.LegalHoldPolicyUpdateRequest): Promise<models.schemas.LegalHoldPolicy> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policies";
    url += '/' + pathEscape(legalHoldPolicyId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.LegalHoldPolicy;
  }

  async delete_(legalHoldPolicyId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policies";
    url += '/' + pathEscape(legalHoldPolicyId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
