// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for LegalHoldPolicyAssignmentsManager.list. */
export interface LegalHoldPolicyAssignmentsManagerListOptions {
  assign_to_type?: models.schemas.LegalHoldPolicyAssignedItemType;
  assign_to_id?: string;
  marker?: string;
  limit?: number;
  fields?: Array<string>;
}

/** Optional parameters for LegalHoldPolicyAssignmentsManager.listFileOnHold. */
export interface LegalHoldPolicyAssignmentsManagerListFileOnHoldOptions {
  marker?: string;
  limit?: number;
  fields?: Array<string>;
}

/** Optional parameters for LegalHoldPolicyAssignmentsManager.listFileVersionOnHold. */
export interface LegalHoldPolicyAssignmentsManagerListFileVersionOnHoldOptions {
  marker?: string;
  limit?: number;
  fields?: Array<string>;
}

/** Operations for the "legal_hold_policy_assignments" API area. */
export class LegalHoldPolicyAssignmentsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.LegalHoldPolicyAssignment` across pages, threading the marker cursor. */
  async *list(policyId: string, opts?: LegalHoldPolicyAssignmentsManagerListOptions): AsyncIterableIterator<models.schemas.LegalHoldPolicyAssignment> {
    const options: LegalHoldPolicyAssignmentsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(policyId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(policyId: string, opts?: LegalHoldPolicyAssignmentsManagerListOptions): Promise<models.schemas.LegalHoldPolicyAssignments> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policy_assignments";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "policy_id", policyId);
    const options = opts ?? {};
    if (options.assign_to_type !== undefined) {
      req = runtime.withQuery(req, "assign_to_type", options.assign_to_type);
    }
    if (options.assign_to_id !== undefined) {
      req = runtime.withQuery(req, "assign_to_id", options.assign_to_id);
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.LegalHoldPolicyAssignments;
  }

  async create(body: models.schemas.LegalHoldPolicyAssignmentCreateRequest): Promise<models.schemas.LegalHoldPolicyAssignment> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policy_assignments";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.LegalHoldPolicyAssignment;
  }

  async get(legalHoldPolicyAssignmentId: string): Promise<models.schemas.LegalHoldPolicyAssignment> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policy_assignments";
    url += '/' + pathEscape(legalHoldPolicyAssignmentId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.LegalHoldPolicyAssignment;
  }

  async delete_(legalHoldPolicyAssignmentId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policy_assignments";
    url += '/' + pathEscape(legalHoldPolicyAssignmentId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  /** Iterate every `models.schemas.FileMini` across pages, threading the marker cursor. */
  async *listFileOnHold(legalHoldPolicyAssignmentId: string, opts?: LegalHoldPolicyAssignmentsManagerListFileOnHoldOptions): AsyncIterableIterator<models.schemas.FileMini> {
    const options: LegalHoldPolicyAssignmentsManagerListFileOnHoldOptions = { ...opts };
    for (;;) {
      const page = await this.listFileOnHoldPage(legalHoldPolicyAssignmentId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFileOnHoldPage(legalHoldPolicyAssignmentId: string, opts?: LegalHoldPolicyAssignmentsManagerListFileOnHoldOptions): Promise<models.schemas.FilesOnHold> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policy_assignments";
    url += '/' + pathEscape(legalHoldPolicyAssignmentId);
    url += "/files_on_hold";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FilesOnHold;
  }

  /** Iterate every `models.schemas.FileVersion` across pages, threading the marker cursor. */
  async *listFileVersionOnHold(legalHoldPolicyAssignmentId: string, opts?: LegalHoldPolicyAssignmentsManagerListFileVersionOnHoldOptions): AsyncIterableIterator<models.schemas.FileVersion> {
    const options: LegalHoldPolicyAssignmentsManagerListFileVersionOnHoldOptions = { ...opts };
    for (;;) {
      const page = await this.listFileVersionOnHoldPage(legalHoldPolicyAssignmentId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFileVersionOnHoldPage(legalHoldPolicyAssignmentId: string, opts?: LegalHoldPolicyAssignmentsManagerListFileVersionOnHoldOptions): Promise<models.schemas.FileVersionsOnHold> {
    let url = this.session.baseUrl("api");
    url += "/legal_hold_policy_assignments";
    url += '/' + pathEscape(legalHoldPolicyAssignmentId);
    url += "/file_versions_on_hold";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FileVersionsOnHold;
  }
}
