// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for ListCollaborationsManager.listFileCollaborations. */
export interface ListCollaborationsManagerListFileCollaborationsOptions {
  fields?: Array<string>;
  limit?: number;
  marker?: string;
}

/** Optional parameters for ListCollaborationsManager.listFolderCollaborations. */
export interface ListCollaborationsManagerListFolderCollaborationsOptions {
  fields?: Array<string>;
  limit?: number;
  marker?: string;
}

/** Optional parameters for ListCollaborationsManager.listCollaborations. */
export interface ListCollaborationsManagerListCollaborationsOptions {
  fields?: Array<string>;
  offset?: number;
  limit?: number;
}

/** Optional parameters for ListCollaborationsManager.listGroupCollaborations. */
export interface ListCollaborationsManagerListGroupCollaborationsOptions {
  limit?: number;
  offset?: number;
}

/** Operations for the "list_collaborations" API area. */
export class ListCollaborationsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.Collaboration` across pages, threading the marker cursor. */
  async *listFileCollaborations(fileId: string, opts?: ListCollaborationsManagerListFileCollaborationsOptions): AsyncIterableIterator<models.schemas.Collaboration> {
    const options: ListCollaborationsManagerListFileCollaborationsOptions = { ...opts };
    for (;;) {
      const page = await this.listFileCollaborationsPage(fileId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFileCollaborationsPage(fileId: string, opts?: ListCollaborationsManagerListFileCollaborationsOptions): Promise<models.schemas.Collaborations> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/collaborations";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Collaborations;
  }

  /** Iterate every `models.schemas.Collaboration` across pages, threading the marker cursor. */
  async *listFolderCollaborations(folderId: string, opts?: ListCollaborationsManagerListFolderCollaborationsOptions): AsyncIterableIterator<models.schemas.Collaboration> {
    const options: ListCollaborationsManagerListFolderCollaborationsOptions = { ...opts };
    for (;;) {
      const page = await this.listFolderCollaborationsPage(folderId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFolderCollaborationsPage(folderId: string, opts?: ListCollaborationsManagerListFolderCollaborationsOptions): Promise<models.schemas.Collaborations> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/collaborations";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Collaborations;
  }

  /** Iterate every `models.schemas.Collaboration` across pages, threading the offset cursor. */
  async *listCollaborations(status: models.schemas.GetCollaborationsStatus, opts?: ListCollaborationsManagerListCollaborationsOptions): AsyncIterableIterator<models.schemas.Collaboration> {
    const options: ListCollaborationsManagerListCollaborationsOptions = { ...opts };
    for (;;) {
      const page = await this.listCollaborationsPage(status, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listCollaborationsPage(status: models.schemas.GetCollaborationsStatus, opts?: ListCollaborationsManagerListCollaborationsOptions): Promise<models.schemas.CollaborationsOffsetPaginated> {
    let url = this.session.baseUrl("api");
    url += "/collaborations";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "status", status);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CollaborationsOffsetPaginated;
  }

  /** Iterate every `models.schemas.Collaboration` across pages, threading the offset cursor. */
  async *listGroupCollaborations(groupId: string, opts?: ListCollaborationsManagerListGroupCollaborationsOptions): AsyncIterableIterator<models.schemas.Collaboration> {
    const options: ListCollaborationsManagerListGroupCollaborationsOptions = { ...opts };
    for (;;) {
      const page = await this.listGroupCollaborationsPage(groupId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listGroupCollaborationsPage(groupId: string, opts?: ListCollaborationsManagerListGroupCollaborationsOptions): Promise<models.schemas.CollaborationsOffsetPaginated> {
    let url = this.session.baseUrl("api");
    url += "/groups";
    url += '/' + pathEscape(groupId);
    url += "/collaborations";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.CollaborationsOffsetPaginated;
  }
}
