// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for MembershipsManager.listUser. */
export interface MembershipsManagerListUserOptions {
  limit?: number;
  offset?: number;
}

/** Optional parameters for MembershipsManager.listGroup. */
export interface MembershipsManagerListGroupOptions {
  limit?: number;
  offset?: number;
}

/** Optional parameters for MembershipsManager.createGroup. */
export interface MembershipsManagerCreateGroupOptions {
  fields?: Array<string>;
}

/** Optional parameters for MembershipsManager.getGroup. */
export interface MembershipsManagerGetGroupOptions {
  fields?: Array<string>;
}

/** Optional parameters for MembershipsManager.updateGroup. */
export interface MembershipsManagerUpdateGroupOptions {
  fields?: Array<string>;
}

/** Operations for the "memberships" API area. */
export class MembershipsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.GroupMembership` across pages, threading the offset cursor. */
  async *listUser(userId: string, opts?: MembershipsManagerListUserOptions): AsyncIterableIterator<models.schemas.GroupMembership> {
    const options: MembershipsManagerListUserOptions = { ...opts };
    for (;;) {
      const page = await this.listUserPage(userId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listUserPage(userId: string, opts?: MembershipsManagerListUserOptions): Promise<models.schemas.GroupMemberships> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    url += "/memberships";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.GroupMemberships;
  }

  /** Iterate every `models.schemas.GroupMembership` across pages, threading the offset cursor. */
  async *listGroup(groupId: string, opts?: MembershipsManagerListGroupOptions): AsyncIterableIterator<models.schemas.GroupMembership> {
    const options: MembershipsManagerListGroupOptions = { ...opts };
    for (;;) {
      const page = await this.listGroupPage(groupId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      if (items.length === 0) {
        return;
      }
      options.offset = (options.offset ?? 0) + items.length;
    }
  }

  private async listGroupPage(groupId: string, opts?: MembershipsManagerListGroupOptions): Promise<models.schemas.GroupMemberships> {
    let url = this.session.baseUrl("api");
    url += "/groups";
    url += '/' + pathEscape(groupId);
    url += "/memberships";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.GroupMemberships;
  }

  async createGroup(body: models.schemas.GroupCreateRequest2, opts?: MembershipsManagerCreateGroupOptions): Promise<models.schemas.GroupMembership> {
    let url = this.session.baseUrl("api");
    url += "/group_memberships";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.GroupMembership;
  }

  async getGroup(groupMembershipId: string, opts?: MembershipsManagerGetGroupOptions): Promise<models.schemas.GroupMembership> {
    let url = this.session.baseUrl("api");
    url += "/group_memberships";
    url += '/' + pathEscape(groupMembershipId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.GroupMembership;
  }

  async updateGroup(groupMembershipId: string, body: models.schemas.GroupUpdateRequest2, opts?: MembershipsManagerUpdateGroupOptions): Promise<models.schemas.GroupMembership> {
    let url = this.session.baseUrl("api");
    url += "/group_memberships";
    url += '/' + pathEscape(groupMembershipId);
    let req = this.session.newRequest("PUT", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.GroupMembership;
  }

  async deleteGroup(groupMembershipId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/group_memberships";
    url += '/' + pathEscape(groupMembershipId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
