// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for MetadataCascadePoliciesManager.list. */
export interface MetadataCascadePoliciesManagerListOptions {
  owner_enterprise_id?: string;
  marker?: string;
  offset?: number;
}

/** Operations for the "metadata_cascade_policies" API area. */
export class MetadataCascadePoliciesManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.MetadataCascadePolicy` across pages, threading the marker cursor. */
  async *list(folderId: string, opts?: MetadataCascadePoliciesManagerListOptions): AsyncIterableIterator<models.schemas.MetadataCascadePolicy> {
    const options: MetadataCascadePoliciesManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(folderId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(folderId: string, opts?: MetadataCascadePoliciesManagerListOptions): Promise<models.schemas.MetadataCascadePolicies> {
    let url = this.session.baseUrl("api");
    url += "/metadata_cascade_policies";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "folder_id", folderId);
    const options = opts ?? {};
    if (options.owner_enterprise_id !== undefined) {
      req = runtime.withQuery(req, "owner_enterprise_id", options.owner_enterprise_id);
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataCascadePolicies;
  }

  async create(body: models.schemas.MetadataCascadePolicyCreateRequest): Promise<models.schemas.MetadataCascadePolicy> {
    let url = this.session.baseUrl("api");
    url += "/metadata_cascade_policies";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataCascadePolicy;
  }

  async get(metadataCascadePolicyId: string): Promise<models.schemas.MetadataCascadePolicy> {
    let url = this.session.baseUrl("api");
    url += "/metadata_cascade_policies";
    url += '/' + pathEscape(metadataCascadePolicyId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataCascadePolicy;
  }

  async delete_(metadataCascadePolicyId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/metadata_cascade_policies";
    url += '/' + pathEscape(metadataCascadePolicyId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  async apply(metadataCascadePolicyId: string, body: models.schemas.MetadataCascadePolicyApplyRequest): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/metadata_cascade_policies";
    url += '/' + pathEscape(metadataCascadePolicyId);
    url += "/apply";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    await this.session.fetch(req);
  }
}
