// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { join, pathEscape } from '../internal.js';

/** Optional parameters for MetadataTaxonomiesManager.list. */
export interface MetadataTaxonomiesManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Optional parameters for MetadataTaxonomiesManager.listNodes. */
export interface MetadataTaxonomiesManagerListNodesOptions {
  level?: Array<number>;
  parent?: Array<string>;
  ancestor?: Array<string>;
  query?: string;
  "include-total-result-count"?: boolean;
  marker?: string;
  limit?: number;
}

/** Optional parameters for MetadataTaxonomiesManager.listMetadataTemplateFieldOptions. */
export interface MetadataTaxonomiesManagerListMetadataTemplateFieldOptionsOptions {
  level?: Array<number>;
  parent?: Array<string>;
  ancestor?: Array<string>;
  query?: string;
  "include-total-result-count"?: boolean;
  "only-selectable-options"?: boolean;
  marker?: string;
  limit?: number;
}

/** Operations for the "metadata_taxonomies" API area. */
export class MetadataTaxonomiesManager {
  constructor(private readonly session: runtime.Client) {}

  async create(body: models.schemas.MetadataTaxonomyCreateRequest): Promise<models.schemas.MetadataTaxonomy> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomy;
  }

  /** Iterate every `models.schemas.MetadataTaxonomy` across pages, threading the marker cursor. */
  async *list(namespace: string, opts?: MetadataTaxonomiesManagerListOptions): AsyncIterableIterator<models.schemas.MetadataTaxonomy> {
    const options: MetadataTaxonomiesManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(namespace, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(namespace: string, opts?: MetadataTaxonomiesManagerListOptions): Promise<models.schemas.MetadataTaxonomies> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomies;
  }

  async get(namespace: string, taxonomyKey: string): Promise<models.schemas.MetadataTaxonomy> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomy;
  }

  async delete_(namespace: string, taxonomyKey: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  async update(namespace: string, taxonomyKey: string, body: models.schemas.MetadataTaxonomyUpdateRequest): Promise<models.schemas.MetadataTaxonomy> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    let req = this.session.newRequest("PATCH", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomy;
  }

  async createLevels(namespace: string, taxonomyKey: string, body: Array<models.schemas.MetadataTaxonomyLevel>): Promise<models.schemas.MetadataTaxonomyLevels> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/levels";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyLevels;
  }

  async updateLevel(namespace: string, taxonomyKey: string, levelIndex: number, body: models.schemas.LevelUpdateRequest): Promise<models.schemas.MetadataTaxonomyLevel> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/levels";
    url += '/' + pathEscape(String(levelIndex));
    let req = this.session.newRequest("PATCH", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyLevel;
  }

  async appendLevels(namespace: string, taxonomyKey: string, body: models.schemas.LevelUpdateRequest): Promise<models.schemas.MetadataTaxonomyLevels> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/levels:append";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyLevels;
  }

  async trimLevels(namespace: string, taxonomyKey: string): Promise<models.schemas.MetadataTaxonomyLevels> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/levels:trim";
    let req = this.session.newRequest("POST", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyLevels;
  }

  /** Iterate every `models.schemas.MetadataTaxonomyNode` across pages, threading the marker cursor. */
  async *listNodes(namespace: string, taxonomyKey: string, opts?: MetadataTaxonomiesManagerListNodesOptions): AsyncIterableIterator<models.schemas.MetadataTaxonomyNode> {
    const options: MetadataTaxonomiesManagerListNodesOptions = { ...opts };
    for (;;) {
      const page = await this.listNodesPage(namespace, taxonomyKey, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listNodesPage(namespace: string, taxonomyKey: string, opts?: MetadataTaxonomiesManagerListNodesOptions): Promise<models.schemas.MetadataTaxonomyNodes> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/nodes";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.level !== undefined) {
      req = runtime.withQuery(req, "level", join(options.level, (v) => String(v)));
    }
    if (options.parent !== undefined) {
      req = runtime.withQuery(req, "parent", options.parent.join(','));
    }
    if (options.ancestor !== undefined) {
      req = runtime.withQuery(req, "ancestor", options.ancestor.join(','));
    }
    if (options.query !== undefined) {
      req = runtime.withQuery(req, "query", options.query);
    }
    if (options["include-total-result-count"] !== undefined) {
      req = runtime.withQuery(req, "include-total-result-count", String(options["include-total-result-count"]));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyNodes;
  }

  async createNodes(namespace: string, taxonomyKey: string, body: models.schemas.NodesCreateRequest): Promise<models.schemas.MetadataTaxonomyNode> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/nodes";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyNode;
  }

  async getNode(namespace: string, taxonomyKey: string, nodeId: string): Promise<models.schemas.MetadataTaxonomyNode> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/nodes";
    url += '/' + pathEscape(nodeId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyNode;
  }

  async deleteNode(namespace: string, taxonomyKey: string, nodeId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/nodes";
    url += '/' + pathEscape(nodeId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  async updateNode(namespace: string, taxonomyKey: string, nodeId: string, body: models.schemas.NodeUpdateRequest): Promise<models.schemas.MetadataTaxonomyNode> {
    let url = this.session.baseUrl("api");
    url += "/metadata_taxonomies";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(taxonomyKey);
    url += "/nodes";
    url += '/' + pathEscape(nodeId);
    let req = this.session.newRequest("PATCH", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyNode;
  }

  /** Iterate every `models.schemas.MetadataTaxonomyNode` across pages, threading the marker cursor. */
  async *listMetadataTemplateFieldOptions(namespace: string, templateKey: string, fieldKey: string, opts?: MetadataTaxonomiesManagerListMetadataTemplateFieldOptionsOptions): AsyncIterableIterator<models.schemas.MetadataTaxonomyNode> {
    const options: MetadataTaxonomiesManagerListMetadataTemplateFieldOptionsOptions = { ...opts };
    for (;;) {
      const page = await this.listMetadataTemplateFieldOptionsPage(namespace, templateKey, fieldKey, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listMetadataTemplateFieldOptionsPage(namespace: string, templateKey: string, fieldKey: string, opts?: MetadataTaxonomiesManagerListMetadataTemplateFieldOptionsOptions): Promise<models.schemas.MetadataTaxonomyNodes> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += '/' + pathEscape(namespace);
    url += '/' + pathEscape(templateKey);
    url += "/fields";
    url += '/' + pathEscape(fieldKey);
    url += "/options";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.level !== undefined) {
      req = runtime.withQuery(req, "level", join(options.level, (v) => String(v)));
    }
    if (options.parent !== undefined) {
      req = runtime.withQuery(req, "parent", options.parent.join(','));
    }
    if (options.ancestor !== undefined) {
      req = runtime.withQuery(req, "ancestor", options.ancestor.join(','));
    }
    if (options.query !== undefined) {
      req = runtime.withQuery(req, "query", options.query);
    }
    if (options["include-total-result-count"] !== undefined) {
      req = runtime.withQuery(req, "include-total-result-count", String(options["include-total-result-count"]));
    }
    if (options["only-selectable-options"] !== undefined) {
      req = runtime.withQuery(req, "only-selectable-options", String(options["only-selectable-options"]));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTaxonomyNodes;
  }
}
