// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for MetadataTemplatesManager.list. */
export interface MetadataTemplatesManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Optional parameters for MetadataTemplatesManager.listGlobal. */
export interface MetadataTemplatesManagerListGlobalOptions {
  marker?: string;
  limit?: number;
}

/** Optional parameters for MetadataTemplatesManager.listEnterprise. */
export interface MetadataTemplatesManagerListEnterpriseOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "metadata_templates" API area. */
export class MetadataTemplatesManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.MetadataTemplate` across pages, threading the marker cursor. */
  async *list(metadataInstanceId: string, opts?: MetadataTemplatesManagerListOptions): AsyncIterableIterator<models.schemas.MetadataTemplate> {
    const options: MetadataTemplatesManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(metadataInstanceId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(metadataInstanceId: string, opts?: MetadataTemplatesManagerListOptions): Promise<models.schemas.MetadataTemplates> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "metadata_instance_id", metadataInstanceId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTemplates;
  }

  async getSchema(scope: models.schemas.GetFileIdMetadataIdIdScope, templateKey: string): Promise<models.schemas.MetadataTemplate> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += '/' + pathEscape(scope);
    url += '/' + pathEscape(templateKey);
    url += "/schema";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTemplate;
  }

  async updateSchema(scope: models.schemas.GetFileIdMetadataIdIdScope, templateKey: string, body: Array<models.schemas.SchemaUpdateRequest>): Promise<models.schemas.MetadataTemplate> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += '/' + pathEscape(scope);
    url += '/' + pathEscape(templateKey);
    url += "/schema";
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTemplate;
  }

  async deleteSchema(scope: models.schemas.GetFileIdMetadataIdIdScope, templateKey: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += '/' + pathEscape(scope);
    url += '/' + pathEscape(templateKey);
    url += "/schema";
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  async get(templateId: string): Promise<models.schemas.MetadataTemplate> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += '/' + pathEscape(templateId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTemplate;
  }

  /** Iterate every `models.schemas.MetadataTemplate` across pages, threading the marker cursor. */
  async *listGlobal(opts?: MetadataTemplatesManagerListGlobalOptions): AsyncIterableIterator<models.schemas.MetadataTemplate> {
    const options: MetadataTemplatesManagerListGlobalOptions = { ...opts };
    for (;;) {
      const page = await this.listGlobalPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listGlobalPage(opts?: MetadataTemplatesManagerListGlobalOptions): Promise<models.schemas.MetadataTemplates> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += "/global";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTemplates;
  }

  /** Iterate every `models.schemas.MetadataTemplate` across pages, threading the marker cursor. */
  async *listEnterprise(opts?: MetadataTemplatesManagerListEnterpriseOptions): AsyncIterableIterator<models.schemas.MetadataTemplate> {
    const options: MetadataTemplatesManagerListEnterpriseOptions = { ...opts };
    for (;;) {
      const page = await this.listEnterprisePage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listEnterprisePage(opts?: MetadataTemplatesManagerListEnterpriseOptions): Promise<models.schemas.MetadataTemplates> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += "/enterprise";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTemplates;
  }

  async createSchema(body: models.schemas.SchemaCreateRequest): Promise<models.schemas.MetadataTemplate> {
    let url = this.session.baseUrl("api");
    url += "/metadata_templates";
    url += "/schema";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataTemplate;
  }
}
