// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Operations for the "notes" API area. */
export class NotesManager {
  constructor(private readonly session: runtime.Client) {}

  async convert(body: models.schemas.NotesConvertRequestBody): Promise<models.schemas.NotesConvertResponse> {
    let url = this.session.baseUrl("api");
    url += "/notes";
    url += "/convert";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2026.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.NotesConvertResponse;
  }
}
