// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Optional parameters for RecentItemsManager.list. */
export interface RecentItemsManagerListOptions {
  fields?: Array<string>;
  limit?: number;
  marker?: string;
}

/** Operations for the "recent_items" API area. */
export class RecentItemsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.RecentItem` across pages, threading the marker cursor. */
  async *list(opts?: RecentItemsManagerListOptions): AsyncIterableIterator<models.schemas.RecentItem> {
    const options: RecentItemsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: RecentItemsManagerListOptions): Promise<models.schemas.RecentItems> {
    let url = this.session.baseUrl("api");
    url += "/recent_items";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RecentItems;
  }
}
