// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for RetentionPoliciesManager.list. */
export interface RetentionPoliciesManagerListOptions {
  policy_name?: string;
  policy_type?: models.schemas.RetentionPolicyPolicyType;
  created_by_user_id?: string;
  fields?: Array<string>;
  limit?: number;
  marker?: string;
}

/** Optional parameters for RetentionPoliciesManager.get. */
export interface RetentionPoliciesManagerGetOptions {
  fields?: Array<string>;
}

/** Operations for the "retention_policies" API area. */
export class RetentionPoliciesManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.RetentionPolicy` across pages, threading the marker cursor. */
  async *list(opts?: RetentionPoliciesManagerListOptions): AsyncIterableIterator<models.schemas.RetentionPolicy> {
    const options: RetentionPoliciesManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: RetentionPoliciesManagerListOptions): Promise<models.schemas.RetentionPolicies> {
    let url = this.session.baseUrl("api");
    url += "/retention_policies";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.policy_name !== undefined) {
      req = runtime.withQuery(req, "policy_name", options.policy_name);
    }
    if (options.policy_type !== undefined) {
      req = runtime.withQuery(req, "policy_type", options.policy_type);
    }
    if (options.created_by_user_id !== undefined) {
      req = runtime.withQuery(req, "created_by_user_id", options.created_by_user_id);
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RetentionPolicies;
  }

  async create(body: models.schemas.RetentionPolicyCreateRequest): Promise<models.schemas.RetentionPolicy> {
    let url = this.session.baseUrl("api");
    url += "/retention_policies";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RetentionPolicy;
  }

  async get(retentionPolicyId: string, opts?: RetentionPoliciesManagerGetOptions): Promise<models.schemas.RetentionPolicy> {
    let url = this.session.baseUrl("api");
    url += "/retention_policies";
    url += '/' + pathEscape(retentionPolicyId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RetentionPolicy;
  }

  async update(retentionPolicyId: string, body: models.schemas.RetentionPolicyUpdateRequest): Promise<models.schemas.RetentionPolicy> {
    let url = this.session.baseUrl("api");
    url += "/retention_policies";
    url += '/' + pathEscape(retentionPolicyId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RetentionPolicy;
  }

  async delete_(retentionPolicyId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/retention_policies";
    url += '/' + pathEscape(retentionPolicyId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
