// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for RetentionPolicyAssignmentsManager.listRetentionPolicyAssignments. */
export interface RetentionPolicyAssignmentsManagerListRetentionPolicyAssignmentsOptions {
  type?: models.schemas.AssignedToType;
  fields?: Array<string>;
  marker?: string;
  limit?: number;
}

/** Optional parameters for RetentionPolicyAssignmentsManager.get. */
export interface RetentionPolicyAssignmentsManagerGetOptions {
  fields?: Array<string>;
}

/** Optional parameters for RetentionPolicyAssignmentsManager.listFileUnderRetention. */
export interface RetentionPolicyAssignmentsManagerListFileUnderRetentionOptions {
  marker?: string;
  limit?: number;
}

/** Optional parameters for RetentionPolicyAssignmentsManager.listFileVersionUnderRetention. */
export interface RetentionPolicyAssignmentsManagerListFileVersionUnderRetentionOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "retention_policy_assignments" API area. */
export class RetentionPolicyAssignmentsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.RetentionPolicyAssignment` across pages, threading the marker cursor. */
  async *listRetentionPolicyAssignments(retentionPolicyId: string, opts?: RetentionPolicyAssignmentsManagerListRetentionPolicyAssignmentsOptions): AsyncIterableIterator<models.schemas.RetentionPolicyAssignment> {
    const options: RetentionPolicyAssignmentsManagerListRetentionPolicyAssignmentsOptions = { ...opts };
    for (;;) {
      const page = await this.listRetentionPolicyAssignmentsPage(retentionPolicyId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listRetentionPolicyAssignmentsPage(retentionPolicyId: string, opts?: RetentionPolicyAssignmentsManagerListRetentionPolicyAssignmentsOptions): Promise<models.schemas.RetentionPolicyAssignments> {
    let url = this.session.baseUrl("api");
    url += "/retention_policies";
    url += '/' + pathEscape(retentionPolicyId);
    url += "/assignments";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.type !== undefined) {
      req = runtime.withQuery(req, "type", options.type);
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RetentionPolicyAssignments;
  }

  async create(body: models.schemas.RetentionPolicyAssignmentCreateRequest): Promise<models.schemas.RetentionPolicyAssignment> {
    let url = this.session.baseUrl("api");
    url += "/retention_policy_assignments";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RetentionPolicyAssignment;
  }

  async get(retentionPolicyAssignmentId: string, opts?: RetentionPolicyAssignmentsManagerGetOptions): Promise<models.schemas.RetentionPolicyAssignment> {
    let url = this.session.baseUrl("api");
    url += "/retention_policy_assignments";
    url += '/' + pathEscape(retentionPolicyAssignmentId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.RetentionPolicyAssignment;
  }

  async delete_(retentionPolicyAssignmentId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/retention_policy_assignments";
    url += '/' + pathEscape(retentionPolicyAssignmentId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  /** Iterate every `models.schemas.FileMini` across pages, threading the marker cursor. */
  async *listFileUnderRetention(retentionPolicyAssignmentId: string, opts?: RetentionPolicyAssignmentsManagerListFileUnderRetentionOptions): AsyncIterableIterator<models.schemas.FileMini> {
    const options: RetentionPolicyAssignmentsManagerListFileUnderRetentionOptions = { ...opts };
    for (;;) {
      const page = await this.listFileUnderRetentionPage(retentionPolicyAssignmentId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFileUnderRetentionPage(retentionPolicyAssignmentId: string, opts?: RetentionPolicyAssignmentsManagerListFileUnderRetentionOptions): Promise<models.schemas.FilesUnderRetention> {
    let url = this.session.baseUrl("api");
    url += "/retention_policy_assignments";
    url += '/' + pathEscape(retentionPolicyAssignmentId);
    url += "/files_under_retention";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FilesUnderRetention;
  }

  /** Iterate every `models.schemas.FileMini` across pages, threading the marker cursor. */
  async *listFileVersionUnderRetention(retentionPolicyAssignmentId: string, opts?: RetentionPolicyAssignmentsManagerListFileVersionUnderRetentionOptions): AsyncIterableIterator<models.schemas.FileMini> {
    const options: RetentionPolicyAssignmentsManagerListFileVersionUnderRetentionOptions = { ...opts };
    for (;;) {
      const page = await this.listFileVersionUnderRetentionPage(retentionPolicyAssignmentId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFileVersionUnderRetentionPage(retentionPolicyAssignmentId: string, opts?: RetentionPolicyAssignmentsManagerListFileVersionUnderRetentionOptions): Promise<models.schemas.FilesUnderRetention> {
    let url = this.session.baseUrl("api");
    url += "/retention_policy_assignments";
    url += '/' + pathEscape(retentionPolicyAssignmentId);
    url += "/file_versions_under_retention";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FilesUnderRetention;
  }
}
