// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { join } from '../internal.js';

/** Optional parameters for SearchManager.get. */
export interface SearchManagerGetOptions {
  query?: string;
  scope?: models.schemas.GetScope;
  file_extensions?: Array<string>;
  created_at_range?: Array<string>;
  updated_at_range?: Array<string>;
  size_range?: Array<number>;
  owner_user_ids?: Array<string>;
  recent_updater_user_ids?: Array<string>;
  ancestor_folder_ids?: Array<string>;
  content_types?: Array<models.schemas.GetContentTypes>;
  type?: models.schemas.GetType;
  trash_content?: models.schemas.GetTrashContent;
  mdfilters?: Array<models.schemas.MetadataFilter>;
  sort?: models.schemas.GetSort;
  direction?: models.schemas.GetDirection;
  limit?: number;
  include_recent_shared_links?: boolean;
  fields?: Array<string>;
  offset?: number;
  deleted_user_ids?: Array<string>;
  deleted_at_range?: Array<string>;
}

/** Operations for the "search" API area. */
export class SearchManager {
  constructor(private readonly session: runtime.Client) {}

  async createMetadataQueryExecuteRead(body: models.schemas.MetadataQuery): Promise<models.schemas.MetadataQueryResults> {
    let url = this.session.baseUrl("api");
    url += "/metadata_queries";
    url += "/execute_read";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.MetadataQueryResults;
  }

  async get(opts?: SearchManagerGetOptions): Promise<models.schemas.SearchResultsResponse> {
    let url = this.session.baseUrl("api");
    url += "/search";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.query !== undefined) {
      req = runtime.withQuery(req, "query", options.query);
    }
    if (options.scope !== undefined) {
      req = runtime.withQuery(req, "scope", options.scope);
    }
    if (options.file_extensions !== undefined) {
      req = runtime.withQuery(req, "file_extensions", options.file_extensions.join(','));
    }
    if (options.created_at_range !== undefined) {
      req = runtime.withQuery(req, "created_at_range", options.created_at_range.join(','));
    }
    if (options.updated_at_range !== undefined) {
      req = runtime.withQuery(req, "updated_at_range", options.updated_at_range.join(','));
    }
    if (options.size_range !== undefined) {
      req = runtime.withQuery(req, "size_range", join(options.size_range, (v) => String(v)));
    }
    if (options.owner_user_ids !== undefined) {
      req = runtime.withQuery(req, "owner_user_ids", options.owner_user_ids.join(','));
    }
    if (options.recent_updater_user_ids !== undefined) {
      req = runtime.withQuery(req, "recent_updater_user_ids", options.recent_updater_user_ids.join(','));
    }
    if (options.ancestor_folder_ids !== undefined) {
      req = runtime.withQuery(req, "ancestor_folder_ids", options.ancestor_folder_ids.join(','));
    }
    if (options.content_types !== undefined) {
      req = runtime.withQuery(req, "content_types", join(options.content_types, (v) => v));
    }
    if (options.type !== undefined) {
      req = runtime.withQuery(req, "type", options.type);
    }
    if (options.trash_content !== undefined) {
      req = runtime.withQuery(req, "trash_content", options.trash_content);
    }
    if (options.mdfilters !== undefined) {
      req = runtime.withQuery(req, "mdfilters", JSON.stringify(options.mdfilters));
    }
    if (options.sort !== undefined) {
      req = runtime.withQuery(req, "sort", options.sort);
    }
    if (options.direction !== undefined) {
      req = runtime.withQuery(req, "direction", options.direction);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.include_recent_shared_links !== undefined) {
      req = runtime.withQuery(req, "include_recent_shared_links", String(options.include_recent_shared_links));
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.deleted_user_ids !== undefined) {
      req = runtime.withQuery(req, "deleted_user_ids", options.deleted_user_ids.join(','));
    }
    if (options.deleted_at_range !== undefined) {
      req = runtime.withQuery(req, "deleted_at_range", options.deleted_at_range.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SearchResultsResponse;
  }
}
