// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Operations for the "session_termination" API area. */
export class SessionTerminationManager {
  constructor(private readonly session: runtime.Client) {}

  async createUserTerminateSessions(body: models.schemas.UserTerminateSessionsCreateRequest): Promise<models.schemas.SessionTerminationMessage> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += "/terminate_sessions";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SessionTerminationMessage;
  }

  async createGroupTerminateSessions(body: models.schemas.GroupTerminateSessionsCreateRequest): Promise<models.schemas.SessionTerminationMessage> {
    let url = this.session.baseUrl("api");
    url += "/groups";
    url += "/terminate_sessions";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SessionTerminationMessage;
  }
}
