// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for SharedLinksWebLinksManager.getSharedItemsWebLinks. */
export interface SharedLinksWebLinksManagerGetSharedItemsWebLinksOptions {
  "if-none-match"?: string;
  fields?: Array<string>;
}

/** Operations for the "shared_links_web_links" API area. */
export class SharedLinksWebLinksManager {
  constructor(private readonly session: runtime.Client) {}

  async getSharedItemsWebLinks(boxapi: string, opts?: SharedLinksWebLinksManagerGetSharedItemsWebLinksOptions): Promise<models.schemas.WebLink> {
    let url = this.session.baseUrl("api");
    url += "/shared_items";
    let req = this.session.newRequest("GET", url);
    req = runtime.withHeader(req, "boxapi", boxapi);
    const options = opts ?? {};
    if (options["if-none-match"] !== undefined) {
      req = runtime.withHeader(req, "if-none-match", options["if-none-match"]);
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.WebLink;
  }

  async getWebLinkGetSharedLink(webLinkId: string, fields: string): Promise<models.schemas.WebLink> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "fields", fields);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.WebLink;
  }

  async updateWebLinkAddSharedLink(webLinkId: string, fields: string, body: models.schemas.FileUpdateRequest2): Promise<models.schemas.WebLink> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    let req = this.session.newRequest("PUT", url);
    req = runtime.withQuery(req, "fields", fields);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.WebLink;
  }

  async updateWebLinkUpdateSharedLink(webLinkId: string, fields: string, body: models.schemas.FileUpdateRequest2): Promise<models.schemas.WebLink> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    let req = this.session.newRequest("PUT", url);
    req = runtime.withQuery(req, "fields", fields);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.WebLink;
  }

  async updateWebLinkRemoveSharedLink(webLinkId: string, fields: string, body: models.schemas.FileUpdateRequest3): Promise<models.schemas.WebLink> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    let req = this.session.newRequest("PUT", url);
    req = runtime.withQuery(req, "fields", fields);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.WebLink;
  }
}
