// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Operations for the "shared_links_app_items" API area. */
export class SharedLinksAppItemsManager {
  constructor(private readonly session: runtime.Client) {}

  async getSharedItemsAppItems(boxapi: string): Promise<models.schemas.AppItem> {
    let url = this.session.baseUrl("api");
    url += "/shared_items";
    let req = this.session.newRequest("GET", url);
    req = runtime.withHeader(req, "boxapi", boxapi);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.AppItem;
  }
}
