// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for ShieldInformationBarrierSegmentsManager.list. */
export interface ShieldInformationBarrierSegmentsManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "shield_information_barrier_segments" API area. */
export class ShieldInformationBarrierSegmentsManager {
  constructor(private readonly session: runtime.Client) {}

  async get(shieldInformationBarrierSegmentId: string): Promise<models.schemas.ShieldInformationBarrierSegment> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segments";
    url += '/' + pathEscape(shieldInformationBarrierSegmentId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierSegment;
  }

  async update(shieldInformationBarrierSegmentId: string, body: models.schemas.ShieldInformationBarrierSegmentUpdateRequest): Promise<models.schemas.ShieldInformationBarrierSegment> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segments";
    url += '/' + pathEscape(shieldInformationBarrierSegmentId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierSegment;
  }

  async delete_(shieldInformationBarrierSegmentId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segments";
    url += '/' + pathEscape(shieldInformationBarrierSegmentId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  /** Iterate every `models.schemas.ShieldInformationBarrierSegment` across pages, threading the marker cursor. */
  async *list(shieldInformationBarrierId: string, opts?: ShieldInformationBarrierSegmentsManagerListOptions): AsyncIterableIterator<models.schemas.ShieldInformationBarrierSegment> {
    const options: ShieldInformationBarrierSegmentsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(shieldInformationBarrierId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(shieldInformationBarrierId: string, opts?: ShieldInformationBarrierSegmentsManagerListOptions): Promise<models.schemas.ShieldInformationBarrierSegments> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segments";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "shield_information_barrier_id", shieldInformationBarrierId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierSegments;
  }

  async create(body: models.schemas.ShieldInformationBarrierSegmentCreateRequest): Promise<models.schemas.ShieldInformationBarrierSegment> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segments";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierSegment;
  }
}
