// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for ShieldInformationBarriersManager.list. */
export interface ShieldInformationBarriersManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "shield_information_barriers" API area. */
export class ShieldInformationBarriersManager {
  constructor(private readonly session: runtime.Client) {}

  async get(shieldInformationBarrierId: string): Promise<models.schemas.ShieldInformationBarrier> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barriers";
    url += '/' + pathEscape(shieldInformationBarrierId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrier;
  }

  async createChangeStatus(body: models.schemas.ChangeStatusCreateRequest): Promise<models.schemas.ShieldInformationBarrier> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barriers";
    url += "/change_status";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrier;
  }

  /** Iterate every `models.schemas.ShieldInformationBarrier` across pages, threading the marker cursor. */
  async *list(opts?: ShieldInformationBarriersManagerListOptions): AsyncIterableIterator<models.schemas.ShieldInformationBarrier> {
    const options: ShieldInformationBarriersManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: ShieldInformationBarriersManagerListOptions): Promise<models.schemas.ShieldInformationBarriers> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barriers";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarriers;
  }

  async create(body: models.schemas.ShieldInformationBarrierCreateRequest): Promise<models.schemas.ShieldInformationBarrier> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barriers";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrier;
  }
}
