// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for ShieldInformationBarrierSegmentRestrictionsManager.list. */
export interface ShieldInformationBarrierSegmentRestrictionsManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "shield_information_barrier_segment_restrictions" API area. */
export class ShieldInformationBarrierSegmentRestrictionsManager {
  constructor(private readonly session: runtime.Client) {}

  async get(shieldInformationBarrierSegmentRestrictionId: string): Promise<models.schemas.ShieldInformationBarrierSegmentRestriction> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segment_restrictions";
    url += '/' + pathEscape(shieldInformationBarrierSegmentRestrictionId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierSegmentRestriction;
  }

  async delete_(shieldInformationBarrierSegmentRestrictionId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segment_restrictions";
    url += '/' + pathEscape(shieldInformationBarrierSegmentRestrictionId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  /** Iterate every `models.schemas.ShieldInformationBarrierSegmentRestriction` across pages, threading the marker cursor. */
  async *list(shieldInformationBarrierSegmentId: string, opts?: ShieldInformationBarrierSegmentRestrictionsManagerListOptions): AsyncIterableIterator<models.schemas.ShieldInformationBarrierSegmentRestriction> {
    const options: ShieldInformationBarrierSegmentRestrictionsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(shieldInformationBarrierSegmentId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(shieldInformationBarrierSegmentId: string, opts?: ShieldInformationBarrierSegmentRestrictionsManagerListOptions): Promise<models.schemas.ShieldInformationBarrierSegmentRestrictions> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segment_restrictions";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "shield_information_barrier_segment_id", shieldInformationBarrierSegmentId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierSegmentRestrictions;
  }

  async create(body: models.schemas.ShieldInformationBarrierSegmentRestrictionCreateRequest): Promise<models.schemas.ShieldInformationBarrierSegmentRestriction> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_segment_restrictions";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierSegmentRestriction;
  }
}
