// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "shield_lists" API area. */
export class ShieldListsManager {
  constructor(private readonly session: runtime.Client) {}

  async list(): Promise<models.schemas.ShieldLists> {
    let url = this.session.baseUrl("api");
    url += "/shield_lists";
    let req = this.session.newRequest("GET", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldLists;
  }

  async create(body: models.schemas.ShieldListsCreate): Promise<models.schemas.ShieldList> {
    let url = this.session.baseUrl("api");
    url += "/shield_lists";
    let req = this.session.newRequest("POST", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldList;
  }

  async get(shieldListId: string): Promise<models.schemas.ShieldList> {
    let url = this.session.baseUrl("api");
    url += "/shield_lists";
    url += '/' + pathEscape(shieldListId);
    let req = this.session.newRequest("GET", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldList;
  }

  async update(shieldListId: string, body: models.schemas.ShieldListsUpdate): Promise<models.schemas.ShieldList> {
    let url = this.session.baseUrl("api");
    url += "/shield_lists";
    url += '/' + pathEscape(shieldListId);
    let req = this.session.newRequest("PUT", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldList;
  }

  async delete_(shieldListId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/shield_lists";
    url += '/' + pathEscape(shieldListId);
    let req = this.session.newRequest("DELETE", url);
    req = runtime.withHeader(req, "box-version", "2025.0");
    await this.session.fetch(req);
  }
}
