// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for ShieldInformationBarrierReportsManager.list. */
export interface ShieldInformationBarrierReportsManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "shield_information_barrier_reports" API area. */
export class ShieldInformationBarrierReportsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.ShieldInformationBarrierReport` across pages, threading the marker cursor. */
  async *list(shieldInformationBarrierId: string, opts?: ShieldInformationBarrierReportsManagerListOptions): AsyncIterableIterator<models.schemas.ShieldInformationBarrierReport> {
    const options: ShieldInformationBarrierReportsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(shieldInformationBarrierId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(shieldInformationBarrierId: string, opts?: ShieldInformationBarrierReportsManagerListOptions): Promise<models.schemas.ShieldInformationBarrierReports> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_reports";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "shield_information_barrier_id", shieldInformationBarrierId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierReports;
  }

  async create(body: models.schemas.ShieldInformationBarrierReference): Promise<models.schemas.ShieldInformationBarrierReport> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_reports";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierReport;
  }

  async get(shieldInformationBarrierReportId: string): Promise<models.schemas.ShieldInformationBarrierReport> {
    let url = this.session.baseUrl("api");
    url += "/shield_information_barrier_reports";
    url += '/' + pathEscape(shieldInformationBarrierReportId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ShieldInformationBarrierReport;
  }
}
