// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for SignRequestsManager.list. */
export interface SignRequestsManagerListOptions {
  marker?: string;
  limit?: number;
  senders?: Array<string>;
  shared_requests?: boolean;
}

/** Operations for the "sign_requests" API area. */
export class SignRequestsManager {
  constructor(private readonly session: runtime.Client) {}

  async cancel(signRequestId: string, body: models.schemas.SignRequestCancelRequest): Promise<models.schemas.SignRequest> {
    let url = this.session.baseUrl("api");
    url += "/sign_requests";
    url += '/' + pathEscape(signRequestId);
    url += "/cancel";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SignRequest;
  }

  async resend(signRequestId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/sign_requests";
    url += '/' + pathEscape(signRequestId);
    url += "/resend";
    let req = this.session.newRequest("POST", url);
    await this.session.fetch(req);
  }

  async get(signRequestId: string): Promise<models.schemas.SignRequest> {
    let url = this.session.baseUrl("api");
    url += "/sign_requests";
    url += '/' + pathEscape(signRequestId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SignRequest;
  }

  /** Iterate every `models.schemas.SignRequest` across pages, threading the marker cursor. */
  async *list(opts?: SignRequestsManagerListOptions): AsyncIterableIterator<models.schemas.SignRequest> {
    const options: SignRequestsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: SignRequestsManagerListOptions): Promise<models.schemas.SignRequests> {
    let url = this.session.baseUrl("api");
    url += "/sign_requests";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.senders !== undefined) {
      req = runtime.withQuery(req, "senders", options.senders.join(','));
    }
    if (options.shared_requests !== undefined) {
      req = runtime.withQuery(req, "shared_requests", String(options.shared_requests));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SignRequests;
  }

  async create(body: models.schemas.SignRequestCreateRequest): Promise<models.schemas.SignRequest> {
    let url = this.session.baseUrl("api");
    url += "/sign_requests";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SignRequest;
  }
}
