// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for SignTemplatesManager.list. */
export interface SignTemplatesManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "sign_templates" API area. */
export class SignTemplatesManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.SignTemplate` across pages, threading the marker cursor. */
  async *list(opts?: SignTemplatesManagerListOptions): AsyncIterableIterator<models.schemas.SignTemplate> {
    const options: SignTemplatesManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: SignTemplatesManagerListOptions): Promise<models.schemas.SignTemplates> {
    let url = this.session.baseUrl("api");
    url += "/sign_templates";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SignTemplates;
  }

  async get(templateId: string): Promise<models.schemas.SignTemplate> {
    let url = this.session.baseUrl("api");
    url += "/sign_templates";
    url += '/' + pathEscape(templateId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.SignTemplate;
  }
}
