// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for StoragePolicyAssignmentsManager.list. */
export interface StoragePolicyAssignmentsManagerListOptions {
  marker?: string;
}

/** Operations for the "storage_policy_assignments" API area. */
export class StoragePolicyAssignmentsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.StoragePolicyAssignment` across pages, threading the marker cursor. */
  async *list(resolvedForType: models.schemas.GetResolvedForType, resolvedForId: string, opts?: StoragePolicyAssignmentsManagerListOptions): AsyncIterableIterator<models.schemas.StoragePolicyAssignment> {
    const options: StoragePolicyAssignmentsManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(resolvedForType, resolvedForId, options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(resolvedForType: models.schemas.GetResolvedForType, resolvedForId: string, opts?: StoragePolicyAssignmentsManagerListOptions): Promise<models.schemas.StoragePolicyAssignments> {
    let url = this.session.baseUrl("api");
    url += "/storage_policy_assignments";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "resolved_for_type", resolvedForType);
    req = runtime.withQuery(req, "resolved_for_id", resolvedForId);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.StoragePolicyAssignments;
  }

  async create(body: models.schemas.StoragePolicyAssignmentCreateRequest): Promise<models.schemas.StoragePolicyAssignment> {
    let url = this.session.baseUrl("api");
    url += "/storage_policy_assignments";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.StoragePolicyAssignment;
  }

  async get(storagePolicyAssignmentId: string): Promise<models.schemas.StoragePolicyAssignment> {
    let url = this.session.baseUrl("api");
    url += "/storage_policy_assignments";
    url += '/' + pathEscape(storagePolicyAssignmentId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.StoragePolicyAssignment;
  }

  async update(storagePolicyAssignmentId: string, body: models.schemas.StoragePolicyAssignmentUpdateRequest): Promise<models.schemas.StoragePolicyAssignment> {
    let url = this.session.baseUrl("api");
    url += "/storage_policy_assignments";
    url += '/' + pathEscape(storagePolicyAssignmentId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.StoragePolicyAssignment;
  }

  async delete_(storagePolicyAssignmentId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/storage_policy_assignments";
    url += '/' + pathEscape(storagePolicyAssignmentId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
