// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for StoragePoliciesManager.list. */
export interface StoragePoliciesManagerListOptions {
  fields?: Array<string>;
  marker?: string;
  limit?: number;
}

/** Operations for the "storage_policies" API area. */
export class StoragePoliciesManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.StoragePolicy` across pages, threading the marker cursor. */
  async *list(opts?: StoragePoliciesManagerListOptions): AsyncIterableIterator<models.schemas.StoragePolicy> {
    const options: StoragePoliciesManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: StoragePoliciesManagerListOptions): Promise<models.schemas.StoragePolicies> {
    let url = this.session.baseUrl("api");
    url += "/storage_policies";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.StoragePolicies;
  }

  async get(storagePolicyId: string): Promise<models.schemas.StoragePolicy> {
    let url = this.session.baseUrl("api");
    url += "/storage_policies";
    url += '/' + pathEscape(storagePolicyId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.StoragePolicy;
  }
}
