// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "tasks" API area. */
export class TasksManager {
  constructor(private readonly session: runtime.Client) {}

  async listFile(fileId: string): Promise<models.schemas.Tasks> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/tasks";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Tasks;
  }

  async create(body: models.schemas.TaskCreateRequest): Promise<models.schemas.Task> {
    let url = this.session.baseUrl("api");
    url += "/tasks";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Task;
  }

  async get(taskId: string): Promise<models.schemas.Task> {
    let url = this.session.baseUrl("api");
    url += "/tasks";
    url += '/' + pathEscape(taskId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Task;
  }

  async update(taskId: string, body: models.schemas.TaskUpdateRequest): Promise<models.schemas.Task> {
    let url = this.session.baseUrl("api");
    url += "/tasks";
    url += '/' + pathEscape(taskId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Task;
  }

  async delete_(taskId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/tasks";
    url += '/' + pathEscape(taskId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
