// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "task_assignments" API area. */
export class TaskAssignmentsManager {
  constructor(private readonly session: runtime.Client) {}

  async listTaskAssignments(taskId: string): Promise<models.schemas.TaskAssignments> {
    let url = this.session.baseUrl("api");
    url += "/tasks";
    url += '/' + pathEscape(taskId);
    url += "/assignments";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TaskAssignments;
  }

  async create(body: models.schemas.TaskAssignmentCreateRequest): Promise<models.schemas.TaskAssignment> {
    let url = this.session.baseUrl("api");
    url += "/task_assignments";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TaskAssignment;
  }

  async get(taskAssignmentId: string): Promise<models.schemas.TaskAssignment> {
    let url = this.session.baseUrl("api");
    url += "/task_assignments";
    url += '/' + pathEscape(taskAssignmentId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TaskAssignment;
  }

  async update(taskAssignmentId: string, body: models.schemas.TaskAssignmentUpdateRequest): Promise<models.schemas.TaskAssignment> {
    let url = this.session.baseUrl("api");
    url += "/task_assignments";
    url += '/' + pathEscape(taskAssignmentId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TaskAssignment;
  }

  async delete_(taskAssignmentId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/task_assignments";
    url += '/' + pathEscape(taskAssignmentId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
