// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for TermsOfServiceUserStatusesManager.list. */
export interface TermsOfServiceUserStatusesManagerListOptions {
  user_id?: string;
}

/** Operations for the "terms_of_service_user_statuses" API area. */
export class TermsOfServiceUserStatusesManager {
  constructor(private readonly session: runtime.Client) {}

  async list(tosId: string, opts?: TermsOfServiceUserStatusesManagerListOptions): Promise<models.schemas.TermsOfServiceUserStatuses> {
    let url = this.session.baseUrl("api");
    url += "/terms_of_service_user_statuses";
    let req = this.session.newRequest("GET", url);
    req = runtime.withQuery(req, "tos_id", tosId);
    const options = opts ?? {};
    if (options.user_id !== undefined) {
      req = runtime.withQuery(req, "user_id", options.user_id);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TermsOfServiceUserStatuses;
  }

  async create(body: models.schemas.TermsOfServiceUserStatuseCreateRequest): Promise<models.schemas.TermsOfServiceUserStatus> {
    let url = this.session.baseUrl("api");
    url += "/terms_of_service_user_statuses";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TermsOfServiceUserStatus;
  }

  async update(termsOfServiceUserStatusId: string, body: models.schemas.TermsOfServiceUserStatuseUpdateRequest): Promise<models.schemas.TermsOfServiceUserStatus> {
    let url = this.session.baseUrl("api");
    url += "/terms_of_service_user_statuses";
    url += '/' + pathEscape(termsOfServiceUserStatusId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TermsOfServiceUserStatus;
  }
}
