// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for TermsOfServicesManager.list. */
export interface TermsOfServicesManagerListOptions {
  tos_type?: models.schemas.GetTosType;
}

/** Operations for the "terms_of_services" API area. */
export class TermsOfServicesManager {
  constructor(private readonly session: runtime.Client) {}

  async list(opts?: TermsOfServicesManagerListOptions): Promise<models.schemas.TermsOfServices> {
    let url = this.session.baseUrl("api");
    url += "/terms_of_services";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.tos_type !== undefined) {
      req = runtime.withQuery(req, "tos_type", options.tos_type);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TermsOfServices;
  }

  async create(body: models.schemas.TermsOfServiceCreateRequest): Promise<models.schemas.TermsOfService> {
    let url = this.session.baseUrl("api");
    url += "/terms_of_services";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TermsOfService;
  }

  async get(termsOfServiceId: string): Promise<models.schemas.TermsOfService> {
    let url = this.session.baseUrl("api");
    url += "/terms_of_services";
    url += '/' + pathEscape(termsOfServiceId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TermsOfService;
  }

  async update(termsOfServiceId: string, body: models.schemas.TermsOfServiceUpdateRequest): Promise<models.schemas.TermsOfService> {
    let url = this.session.baseUrl("api");
    url += "/terms_of_services";
    url += '/' + pathEscape(termsOfServiceId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TermsOfService;
  }
}
