// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for TransferManager.transferFolders. */
export interface TransferManagerTransferFoldersOptions {
  fields?: Array<string>;
  notify?: boolean;
}

/** Operations for the "transfer" API area. */
export class TransferManager {
  constructor(private readonly session: runtime.Client) {}

  async transferFolders(userId: string, body: models.schemas.UserFolder0UpdateRequest, opts?: TransferManagerTransferFoldersOptions): Promise<models.schemas.FolderFull> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    url += "/folders";
    url += "/0";
    let req = this.session.newRequest("PUT", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.notify !== undefined) {
      req = runtime.withQuery(req, "notify", String(options.notify));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.FolderFull;
  }
}
