// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for TrashedFilesManager.createFile. */
export interface TrashedFilesManagerCreateFileOptions {
  fields?: Array<string>;
}

/** Optional parameters for TrashedFilesManager.getFileTrash. */
export interface TrashedFilesManagerGetFileTrashOptions {
  fields?: Array<string>;
}

/** Operations for the "trashed_files" API area. */
export class TrashedFilesManager {
  constructor(private readonly session: runtime.Client) {}

  async createFile(fileId: string, body: models.schemas.FileCreateRequest, opts?: TrashedFilesManagerCreateFileOptions): Promise<models.schemas.TrashFileRestored> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TrashFileRestored;
  }

  async getFileTrash(fileId: string, opts?: TrashedFilesManagerGetFileTrashOptions): Promise<models.schemas.TrashFile> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/trash";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TrashFile;
  }

  async deleteFileTrash(fileId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/trash";
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
