// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for TrashedWebLinksManager.createWebLink. */
export interface TrashedWebLinksManagerCreateWebLinkOptions {
  fields?: Array<string>;
}

/** Optional parameters for TrashedWebLinksManager.getWebLinkTrash. */
export interface TrashedWebLinksManagerGetWebLinkTrashOptions {
  fields?: Array<string>;
}

/** Operations for the "trashed_web_links" API area. */
export class TrashedWebLinksManager {
  constructor(private readonly session: runtime.Client) {}

  async createWebLink(webLinkId: string, body: models.schemas.FileCreateRequest, opts?: TrashedWebLinksManagerCreateWebLinkOptions): Promise<models.schemas.TrashWebLinkRestored> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TrashWebLinkRestored;
  }

  async getWebLinkTrash(webLinkId: string, opts?: TrashedWebLinksManagerGetWebLinkTrashOptions): Promise<models.schemas.TrashWebLink> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    url += "/trash";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TrashWebLink;
  }

  async deleteWebLinkTrash(webLinkId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    url += "/trash";
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
