// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for TrashedFoldersManager.createFolder. */
export interface TrashedFoldersManagerCreateFolderOptions {
  fields?: Array<string>;
}

/** Optional parameters for TrashedFoldersManager.getFolderTrash. */
export interface TrashedFoldersManagerGetFolderTrashOptions {
  fields?: Array<string>;
}

/** Operations for the "trashed_folders" API area. */
export class TrashedFoldersManager {
  constructor(private readonly session: runtime.Client) {}

  async createFolder(folderId: string, body: models.schemas.FileCreateRequest, opts?: TrashedFoldersManagerCreateFolderOptions): Promise<models.schemas.TrashFolderRestored> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TrashFolderRestored;
  }

  async getFolderTrash(folderId: string, opts?: TrashedFoldersManagerGetFolderTrashOptions): Promise<models.schemas.TrashFolder> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/trash";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.TrashFolder;
  }

  async deleteFolderTrash(folderId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += '/' + pathEscape(folderId);
    url += "/trash";
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
