// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';

/** Optional parameters for TrashedItemsManager.listFolderTrashItems. */
export interface TrashedItemsManagerListFolderTrashItemsOptions {
  fields?: Array<string>;
  limit?: number;
  offset?: number;
  usemarker?: boolean;
  marker?: string;
  direction?: models.schemas.OrderDirection;
  sort?: models.schemas.GetFolderTrashItemsSort;
}

/** Operations for the "trashed_items" API area. */
export class TrashedItemsManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.Item` across pages, threading the marker cursor. */
  async *listFolderTrashItems(opts?: TrashedItemsManagerListFolderTrashItemsOptions): AsyncIterableIterator<models.schemas.Item> {
    const options: TrashedItemsManagerListFolderTrashItemsOptions = { ...opts };
    for (;;) {
      const page = await this.listFolderTrashItemsPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listFolderTrashItemsPage(opts?: TrashedItemsManagerListFolderTrashItemsOptions): Promise<models.schemas.Items> {
    let url = this.session.baseUrl("api");
    url += "/folders";
    url += "/trash";
    url += "/items";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.usemarker !== undefined) {
      req = runtime.withQuery(req, "usemarker", String(options.usemarker));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.direction !== undefined) {
      req = runtime.withQuery(req, "direction", options.direction);
    }
    if (options.sort !== undefined) {
      req = runtime.withQuery(req, "sort", options.sort);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Items;
  }
}
