// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for UploadsManager.uploadFileVersion. */
export interface UploadsManagerUploadFileVersionOptions {
  "if-match"?: string;
  fields?: Array<string>;
  "content-md5"?: string;
}

/** Optional parameters for UploadsManager.uploadFile. */
export interface UploadsManagerUploadFileOptions {
  fields?: Array<string>;
  "content-md5"?: string;
}

/** Operations for the "uploads" API area. */
export class UploadsManager {
  constructor(private readonly session: runtime.Client) {}

  async uploadFileVersion(fileId: string, body: models.schemas.FileIdContentCreateRequest, opts?: UploadsManagerUploadFileVersionOptions): Promise<models.schemas.Files> {
    let url = this.session.baseUrl("upload");
    url += "/files";
    url += '/' + pathEscape(fileId);
    url += "/content";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options["if-match"] !== undefined) {
      req = runtime.withHeader(req, "if-match", options["if-match"]);
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options["content-md5"] !== undefined) {
      req = runtime.withHeader(req, "content-md5", options["content-md5"]);
    }
    const attributes = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withMultipartBody(req, attributes, 'file', runtime.Stream.empty());
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Files;
  }

  async uploadFile(body: models.schemas.FileContentCreateRequest, opts?: UploadsManagerUploadFileOptions): Promise<models.schemas.Files> {
    let url = this.session.baseUrl("upload");
    url += "/files";
    url += "/content";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options["content-md5"] !== undefined) {
      req = runtime.withHeader(req, "content-md5", options["content-md5"]);
    }
    const attributes = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withMultipartBody(req, attributes, 'file', runtime.Stream.empty());
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Files;
  }

  async optionFileContent(body: models.schemas.OptionFileContentRequest): Promise<models.schemas.UploadUrl> {
    let url = this.session.baseUrl("api");
    url += "/files";
    url += "/content";
    let req = this.session.newRequest("OPTIONS", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UploadUrl;
  }
}
