// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for UserCollaborationsManager.getCollaboration. */
export interface UserCollaborationsManagerGetCollaborationOptions {
  fields?: Array<string>;
}

/** Optional parameters for UserCollaborationsManager.createCollaborations. */
export interface UserCollaborationsManagerCreateCollaborationsOptions {
  fields?: Array<string>;
  notify?: boolean;
}

/** Operations for the "user_collaborations" API area. */
export class UserCollaborationsManager {
  constructor(private readonly session: runtime.Client) {}

  async getCollaboration(collaborationId: string, opts?: UserCollaborationsManagerGetCollaborationOptions): Promise<models.schemas.Collaboration> {
    let url = this.session.baseUrl("api");
    url += "/collaborations";
    url += '/' + pathEscape(collaborationId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Collaboration;
  }

  async updateCollaboration(collaborationId: string, body: models.schemas.CollaborationUpdateRequest): Promise<models.schemas.Collaboration> {
    let url = this.session.baseUrl("api");
    url += "/collaborations";
    url += '/' + pathEscape(collaborationId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Collaboration;
  }

  async deleteCollaboration(collaborationId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/collaborations";
    url += '/' + pathEscape(collaborationId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }

  async createCollaborations(body: models.schemas.CollaborationsCreateRequest, opts?: UserCollaborationsManagerCreateCollaborationsOptions): Promise<models.schemas.Collaboration> {
    let url = this.session.baseUrl("api");
    url += "/collaborations";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.notify !== undefined) {
      req = runtime.withQuery(req, "notify", String(options.notify));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Collaboration;
  }
}
