// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for UsersManager.list. */
export interface UsersManagerListOptions {
  filter_term?: string;
  user_type?: models.schemas.GetUserType;
  external_app_user_id?: string;
  fields?: Array<string>;
  offset?: number;
  limit?: number;
  usemarker?: boolean;
  marker?: string;
}

/** Optional parameters for UsersManager.create. */
export interface UsersManagerCreateOptions {
  fields?: Array<string>;
}

/** Optional parameters for UsersManager.getMe. */
export interface UsersManagerGetMeOptions {
  fields?: Array<string>;
}

/** Optional parameters for UsersManager.get. */
export interface UsersManagerGetOptions {
  fields?: Array<string>;
}

/** Optional parameters for UsersManager.update. */
export interface UsersManagerUpdateOptions {
  fields?: Array<string>;
}

/** Optional parameters for UsersManager.delete_. */
export interface UsersManagerDeleteOptions {
  notify?: boolean;
  force?: boolean;
}

/** Operations for the "users" API area. */
export class UsersManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.UserFull` across pages, threading the marker cursor. */
  async *list(opts?: UsersManagerListOptions): AsyncIterableIterator<models.schemas.UserFull> {
    const options: UsersManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: UsersManagerListOptions): Promise<models.schemas.Users> {
    let url = this.session.baseUrl("api");
    url += "/users";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.filter_term !== undefined) {
      req = runtime.withQuery(req, "filter_term", options.filter_term);
    }
    if (options.user_type !== undefined) {
      req = runtime.withQuery(req, "user_type", options.user_type);
    }
    if (options.external_app_user_id !== undefined) {
      req = runtime.withQuery(req, "external_app_user_id", options.external_app_user_id);
    }
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    if (options.offset !== undefined) {
      req = runtime.withQuery(req, "offset", String(options.offset));
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    if (options.usemarker !== undefined) {
      req = runtime.withQuery(req, "usemarker", String(options.usemarker));
    }
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Users;
  }

  async create(body: models.schemas.UserCreateRequest, opts?: UsersManagerCreateOptions): Promise<models.schemas.UserFull> {
    let url = this.session.baseUrl("api");
    url += "/users";
    let req = this.session.newRequest("POST", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UserFull;
  }

  async getMe(opts?: UsersManagerGetMeOptions): Promise<models.schemas.UserFull> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += "/me";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UserFull;
  }

  async get(userId: string, opts?: UsersManagerGetOptions): Promise<models.schemas.UserFull> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UserFull;
  }

  async update(userId: string, body: models.schemas.UserUpdateRequest, opts?: UsersManagerUpdateOptions): Promise<models.schemas.UserFull> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    let req = this.session.newRequest("PUT", url);
    const options = opts ?? {};
    if (options.fields !== undefined) {
      req = runtime.withQuery(req, "fields", options.fields.join(','));
    }
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.UserFull;
  }

  async delete_(userId: string, opts?: UsersManagerDeleteOptions): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/users";
    url += '/' + pathEscape(userId);
    let req = this.session.newRequest("DELETE", url);
    const options = opts ?? {};
    if (options.notify !== undefined) {
      req = runtime.withQuery(req, "notify", String(options.notify));
    }
    if (options.force !== undefined) {
      req = runtime.withQuery(req, "force", String(options.force));
    }
    await this.session.fetch(req);
  }
}
