// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for WebLinksManager.get. */
export interface WebLinksManagerGetOptions {
  boxapi?: string;
}

/** Operations for the "web_links" API area. */
export class WebLinksManager {
  constructor(private readonly session: runtime.Client) {}

  async create(body: models.schemas.WebLinkCreateRequest): Promise<models.schemas.WebLink> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.WebLink;
  }

  async get(webLinkId: string, opts?: WebLinksManagerGetOptions): Promise<models.schemas.WebLink> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.boxapi !== undefined) {
      req = runtime.withHeader(req, "boxapi", options.boxapi);
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.WebLink;
  }

  async update(webLinkId: string, body: models.schemas.WebLinkUpdateRequest): Promise<models.schemas.WebLink> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.WebLink;
  }

  async delete_(webLinkId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/web_links";
    url += '/' + pathEscape(webLinkId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
