// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Optional parameters for WebhooksManager.list. */
export interface WebhooksManagerListOptions {
  marker?: string;
  limit?: number;
}

/** Operations for the "webhooks" API area. */
export class WebhooksManager {
  constructor(private readonly session: runtime.Client) {}

  /** Iterate every `models.schemas.WebhookMini` across pages, threading the marker cursor. */
  async *list(opts?: WebhooksManagerListOptions): AsyncIterableIterator<models.schemas.WebhookMini> {
    const options: WebhooksManagerListOptions = { ...opts };
    for (;;) {
      const page = await this.listPage(options);
      const items = page.entries ?? [];
      for (const item of items) {
        yield item;
      }
      const cursor = page.next_marker;
      if (cursor === undefined || cursor === null || cursor === '') {
        return;
      }
      options.marker = cursor;
    }
  }

  private async listPage(opts?: WebhooksManagerListOptions): Promise<models.schemas.Webhooks> {
    let url = this.session.baseUrl("api");
    url += "/webhooks";
    let req = this.session.newRequest("GET", url);
    const options = opts ?? {};
    if (options.marker !== undefined) {
      req = runtime.withQuery(req, "marker", options.marker);
    }
    if (options.limit !== undefined) {
      req = runtime.withQuery(req, "limit", String(options.limit));
    }
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Webhooks;
  }

  async create(body: models.schemas.WebhookCreateRequest): Promise<models.schemas.Webhook> {
    let url = this.session.baseUrl("api");
    url += "/webhooks";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Webhook;
  }

  async get(webhookId: string): Promise<models.schemas.Webhook> {
    let url = this.session.baseUrl("api");
    url += "/webhooks";
    url += '/' + pathEscape(webhookId);
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Webhook;
  }

  async update(webhookId: string, body: models.schemas.WebhookUpdateRequest): Promise<models.schemas.Webhook> {
    let url = this.session.baseUrl("api");
    url += "/webhooks";
    url += '/' + pathEscape(webhookId);
    let req = this.session.newRequest("PUT", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.Webhook;
  }

  async delete_(webhookId: string): Promise<void> {
    let url = this.session.baseUrl("api");
    url += "/webhooks";
    url += '/' + pathEscape(webhookId);
    let req = this.session.newRequest("DELETE", url);
    await this.session.fetch(req);
  }
}
