// Code generated by box-gantry. DO NOT EDIT.

import * as runtime from '../runtime.js';
import type * as models from '../models/index.js';
import { pathEscape } from '../internal.js';

/** Operations for the "zip_downloads" API area. */
export class ZipDownloadsManager {
  constructor(private readonly session: runtime.Client) {}

  async create(body: models.schemas.ZipDownloadRequest): Promise<models.schemas.ZipDownload> {
    let url = this.session.baseUrl("api");
    url += "/zip_downloads";
    let req = this.session.newRequest("POST", url);
    const payload = new TextEncoder().encode(JSON.stringify(body));
    req = runtime.withJsonBody(req, payload);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ZipDownload;
  }

  async getContent(zipDownloadId: string): Promise<runtime.Stream> {
    let url = this.session.baseUrl("download");
    url += "/zip_downloads";
    url += '/' + pathEscape(zipDownloadId);
    url += "/content";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    return runtime.responseStream(resp);
  }

  async getStatus(zipDownloadId: string): Promise<models.schemas.ZipDownloadStatus> {
    let url = this.session.baseUrl("api");
    url += "/zip_downloads";
    url += '/' + pathEscape(zipDownloadId);
    url += "/status";
    let req = this.session.newRequest("GET", url);
    const resp = await this.session.fetch(req);
    const data = runtime.responseBytes(resp);
    return JSON.parse(new TextDecoder().decode(data)) as models.schemas.ZipDownloadStatus;
  }
}
