// Code generated by box-gantry. DO NOT EDIT.

// Write the dual-package `type` markers so Node reads `dist/esm` as ES
// modules and `dist/cjs` as CommonJS regardless of the root package type.
import { writeFileSync } from 'node:fs';

writeFileSync('dist/esm/package.json', '{\n  "type": "module"\n}\n');
writeFileSync('dist/cjs/package.json', '{\n  "type": "commonjs"\n}\n');
