// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.

/** The box-gantry engine version that generated this SDK. */
export const ENGINE = "0.1.0";
/** Fingerprint of the input spec set. */
export const SPEC_FINGERPRINT = "ee7d55aedefe2fa0";
/** The target language key (FR-4). */
export const TARGET = "typescript";
