// Code generated by box-gantry. DO NOT EDIT.

import type { Client } from './client.js';
import type * as models from './models/index.js';

/**
 * ChunkedUpload orchestrates a Box chunked (multipart) upload over a Client: it
 * creates an upload session, uploads the content's parts with bounded
 * concurrency, and commits — for a new file (upload) or a new version of an
 * existing file (uploadVersion). Box requires chunked upload for files at or
 * above its minimum session size; smaller files use the single-shot endpoints.
 */
export class ChunkedUpload {
  /** Bounds parts in flight, capping peak memory. */
  private readonly maxConcurrent = 4;

  constructor(private readonly client: Client) {}

  /** Upload content as a new file named fileName into folderId. */
  async upload(content: Uint8Array, fileName: string, folderId: string): Promise<models.schemas.Files> {
    const session = await this.client.chunkedUploads.createFileUploadSession({
      folder_id: folderId,
      file_size: content.length,
      file_name: fileName,
    });
    return this.finish(session, content);
  }

  /** Upload content as a new version of the existing file fileId. */
  async uploadVersion(content: Uint8Array, fileName: string, fileId: string): Promise<models.schemas.Files> {
    const session = await this.client.chunkedUploads.createFileVersionUploadSession(fileId, {
      file_size: content.length,
      file_name: fileName,
    });
    return this.finish(session, content);
  }

  private async finish(session: models.schemas.UploadSession, content: Uint8Array): Promise<models.schemas.Files> {
    if (session.id === undefined) {
      throw new Error('gantry: upload session returned no id');
    }
    if (session.part_size === undefined || session.part_size <= 0) {
      throw new Error('gantry: upload session returned a non-positive part_size');
    }
    const id = session.id;
    const partSize = session.part_size;
    const total = content.length;

    const offsets: number[] = [];
    for (let off = 0; off < total; off += partSize) {
      offsets.push(off);
    }
    const parts: models.schemas.UploadPart[] = new Array(offsets.length);

    // A bounded worker pool: each of maxConcurrent workers claims the next
    // offset (the `next++` read is atomic between awaits on a single thread).
    // Once any part fails, `failed` stops the others from starting new parts,
    // so a failure early in a large upload doesn't push every remaining part.
    let next = 0;
    let failed = false;
    const worker = async (): Promise<void> => {
      for (;;) {
        if (failed) {
          return;
        }
        const i = next++;
        if (i >= offsets.length) {
          return;
        }
        const start = offsets[i];
        const end = Math.min(start + partSize, total);
        try {
          parts[i] = await this.uploadPart(id, content, start, end, total);
        } catch (err) {
          failed = true;
          throw err;
        }
      }
    };
    const workerCount = Math.min(this.maxConcurrent, offsets.length);
    await Promise.all(Array.from({ length: workerCount }, () => worker()));

    const digest = 'sha=' + (await sha1Base64(content));
    return this.client.chunkedUploads.commitFileUploadSession(id, digest, { parts });
  }

  private async uploadPart(id: string, content: Uint8Array, start: number, end: number, total: number): Promise<models.schemas.UploadPart> {
    const slice = content.subarray(start, end);
    const digest = 'sha=' + (await sha1Base64(slice));
    const contentRange = `bytes ${start}-${end - 1}/${total}`;
    // The `as BlobPart` cast bridges the `Uint8Array<ArrayBufferLike>` vs
    // `BufferSource` (ArrayBuffer-only) generic gap in the DOM lib, exactly as
    // the runtime casts its `fetch` body; a plain `Uint8Array` is a valid part.
    const uploaded = await this.client.chunkedUploads.updateFileUploadSession(id, digest, contentRange, new Blob([slice as BlobPart]));
    if (uploaded.part === undefined) {
      throw new Error('gantry: upload part returned no part');
    }
    return uploaded.part;
  }
}

/** Base64 of the SHA-1 of data — the Box `Digest: sha=…` header value. Uses Web
 *  Crypto (browser and Node 18+), so it adds no dependency. */
async function sha1Base64(data: Uint8Array): Promise<string> {
  // `as BufferSource` bridges the `Uint8Array<ArrayBufferLike>` vs ArrayBuffer-only
  // generic gap in the DOM lib (as the runtime does for its `fetch` body).
  const digest = new Uint8Array(await crypto.subtle.digest('SHA-1', data as BufferSource));
  let binary = '';
  for (const byte of digest) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary);
}
