// Code generated by box-gantry. DO NOT EDIT.

/** Comma-join a list into a query value, converting each element with `f`. */
export function join<T>(items: Array<T>, f: (v: T) => string): string {
  return items.map(f).join(',');
}

/** Percent-encode a value, leaving RFC 3986 unreserved characters as-is. */
export function pathEscape(value: string): string {
  let out = '';
  for (const byte of new TextEncoder().encode(value)) {
    const unreserved =
      (byte >= 0x41 && byte <= 0x5a) || // A-Z
      (byte >= 0x61 && byte <= 0x7a) || // a-z
      (byte >= 0x30 && byte <= 0x39) || // 0-9
      byte === 0x2d || // -
      byte === 0x2e || // .
      byte === 0x5f || // _
      byte === 0x7e; //  ~
    if (unreserved) {
      out += String.fromCharCode(byte);
    } else {
      out += '%' + byte.toString(16).toUpperCase().padStart(2, '0');
    }
  }
  return out;
}

/**
 * An application/x-www-form-urlencoded body from key/value pairs (the OAuth2
 * token endpoints): each key and value percent-encoded, joined by `&`.
 */
export function formEncode(pairs: Array<[string, string]>): string {
  return pairs.map(([key, value]) => `${pathEscape(key)}=${pathEscape(value)}`).join('&');
}
