// Code generated by box-gantry. DO NOT EDIT.

declare module 'node:test' {
export function test(name: string, fn: () => void | Promise<void>): void;
}
declare module 'node:assert/strict' {
interface StrictAssert {
equal(actual: unknown, expected: unknown): void;
deepEqual(actual: unknown, expected: unknown): void;
ok(value: unknown): void;
}
const assert: StrictAssert;
export default assert;
}
