// Code generated by gantry-contract — do not edit.
//
// Type-checkable stubs for the hand-written runtime surface (FR-5.3).
// Generated SDK code type-checks against this module; the real runtime
// implements the same contract.
/* eslint-disable */

/** The runtime-owned HTTP request envelope. */
export class Request {}

/** The runtime-owned HTTP response envelope. */
export class Response {}

/** A streaming body (buffered on platforms whose manifest says so). */
export class Stream {
  /** An empty stream (e.g. an absent multipart file part). */
  static empty(): Stream {
    throw new Error('gantryruntime stub: Stream.empty is not wired to a real runtime');
  }
}

/** The configured authentication flow (developer token, CCG, OAuth, JWT). */
export class Auth {}

/** A runtime error: a failed request, auth acquisition, or body decode. */
export class BoxApiError extends Error {}

/**
 * The runtime session: auth, base URLs, HTTP client, retry policy.
 * Session-receiver contract functions are its methods.
 */
export class Client {
  /** Build a runtime session for an authentication flow. */
  constructor(auth: Auth) {
    throw new Error('gantryruntime stub: Client is not wired to a real runtime');
  }

  /** Execute the request with retries: exponential backoff + jitter, 401 token refresh, Retry-After handling (R§1 network layer). */
  async fetch(request: Request, signal?: AbortSignal): Promise<Response> {
    throw new Error('gantryruntime stub: fetch is not wired to a real runtime');
  }

  /** Return a valid access token for the configured auth flow, acquiring or refreshing through the pluggable token store as needed. */
  async accessToken(signal?: AbortSignal): Promise<string> {
    throw new Error('gantryruntime stub: access_token is not wired to a real runtime');
  }

  /** The configured base URL for a D-106 class ("api", "api_root", "upload", "upload_session", "oauth_authorize", "download"), without a trailing slash. Runtime configuration may override any of them (custom deployments). */
  baseUrl(name: string): string {
    throw new Error('gantryruntime stub: base_url is not wired to a real runtime');
  }

  /** Create a request envelope for the given method and fully built URL. */
  newRequest(method: string, url: string): Request {
    throw new Error('gantryruntime stub: new_request is not wired to a real runtime');
  }
}

/** Return the request with the header set. */
export function withHeader(request: Request, name: string, value: string): Request {
  throw new Error('gantryruntime stub: with_header is not wired to a real runtime');
}

/** Return the request with the query parameter appended, encoded. */
export function withQuery(request: Request, name: string, value: string): Request {
  throw new Error('gantryruntime stub: with_query is not wired to a real runtime');
}

/** Return the request with the serialized JSON body and content type set. */
export function withJsonBody(request: Request, body: Uint8Array): Request {
  throw new Error('gantryruntime stub: with_json_body is not wired to a real runtime');
}

/** Return the request with an application/x-www-form-urlencoded body (the OAuth2 token endpoints). */
export function withFormBody(request: Request, form: Uint8Array): Request {
  throw new Error('gantryruntime stub: with_form_body is not wired to a real runtime');
}

/** Return the request with a streaming body (buffered on platforms whose manifest says so — FR-7.4). */
export function withStreamBody(request: Request, body: Stream, contentType: string): Request {
  throw new Error('gantryruntime stub: with_stream_body is not wired to a real runtime');
}

/** Return the request with a Box-style multipart body: an `attributes` JSON part plus a file part (G-7). */
export function withMultipartBody(request: Request, attributes: Uint8Array, fileName: string, file: Stream): Request {
  throw new Error('gantryruntime stub: with_multipart_body is not wired to a real runtime');
}

/** Read the whole response body. */
export function responseBytes(response: Response): Uint8Array {
  throw new Error('gantryruntime stub: response_bytes is not wired to a real runtime');
}

/** The response body as a stream, for binary downloads (FR-7.4). */
export function responseStream(response: Response): Stream {
  throw new Error('gantryruntime stub: response_stream is not wired to a real runtime');
}

/** A response header value, empty when absent (redirect Location, Retry-After surfacing). */
export function responseHeader(response: Response, name: string): string {
  throw new Error('gantryruntime stub: response_header is not wired to a real runtime');
}

/** The response status code. */
export function statusCode(response: Response): number {
  throw new Error('gantryruntime stub: status_code is not wired to a real runtime');
}
