// Code generated by box-gantry. DO NOT EDIT.

// Serialization behavioral tests (VR-4): the tri-state (absent / explicit-null
// / value) through the JSON wire codec, and ISO-8601 date/date-time round-trips.
import { test } from 'node:test';
import assert from 'node:assert/strict';

// The tri-state mapped straight onto the type system (TR-TS.2): absent is an
// omitted key, explicit null is `| null`, a value is the value.
interface TriState {
field?: string | null;
}

test('tri-state serializes absent / null / value distinctly (Box clear-on-update)', () => {
const absent: TriState = {};
assert.equal(JSON.stringify(absent), '{}');
const nulled: TriState = { field: null };
assert.equal(JSON.stringify(nulled), '{\"field\":null}');
const valued: TriState = { field: 'x' };
assert.equal(JSON.stringify(valued), '{\"field\":\"x\"}');
});

test('tri-state deserializes absent / null / value distinctly', () => {
const valued = JSON.parse('{\"field\":\"y\"}') as TriState;
assert.equal(valued.field, 'y');
const nulled = JSON.parse('{\"field\":null}') as TriState;
assert.equal(nulled.field, null);
const absent = JSON.parse('{}') as TriState;
assert.equal(absent.field, undefined);
// Absent is distinguishable from null: the key is simply not present.
assert.equal('field' in absent, false);
assert.equal('field' in nulled, true);
});

test('ISO-8601 date and date-time strings round-trip through JSON', () => {
// Box dates/date-times are ISO strings on the wire (TR-TS.2); JSON preserves them.
const date = JSON.parse('{\"d\":\"2026-07-12\"}') as { d: string };
assert.equal(date.d, '2026-07-12');
assert.equal(JSON.stringify(date), '{\"d\":\"2026-07-12\"}');
const dt = JSON.parse('{\"t\":\"2026-07-12T08:30:00Z\"}') as { t: string };
assert.equal(dt.t, '2026-07-12T08:30:00Z');
});
