// Code generated by box-gantry. DO NOT EDIT.

// Per-union round-trip tests (VR-4): known-tag dispatch, and open-union
// unknown-tag retention via the `{ [key: string]: unknown }` catch-all.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import type * as models from './models/index.js';

test('schemas.AiAgent dispatches on type — known ai_agent_ask, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"ai_agent_ask\"}") as models.schemas.AiAgent;
  assert.equal((known as Record<string, unknown>)["type"], "ai_agent_ask");
  const unknown: models.schemas.AiAgent = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.AiAgentAllowedEntity dispatches on type — known user, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"user\"}") as models.schemas.AiAgentAllowedEntity;
  assert.equal((known as Record<string, unknown>)["type"], "user");
  const unknown: models.schemas.AiAgentAllowedEntity = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.AiAskAgent dispatches on type — known ai_agent_id, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"ai_agent_id\"}") as models.schemas.AiAskAgent;
  assert.equal((known as Record<string, unknown>)["type"], "ai_agent_id");
  const unknown: models.schemas.AiAskAgent = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.AiExtractAgent dispatches on type — known ai_agent_id, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"ai_agent_id\"}") as models.schemas.AiExtractAgent;
  assert.equal((known as Record<string, unknown>)["type"], "ai_agent_id");
  const unknown: models.schemas.AiExtractAgent = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.AiExtractStructuredAgent dispatches on type — known ai_agent_id, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"ai_agent_id\"}") as models.schemas.AiExtractStructuredAgent;
  assert.equal((known as Record<string, unknown>)["type"], "ai_agent_id");
  const unknown: models.schemas.AiExtractStructuredAgent = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.AiLlmEndpointParams dispatches on type — known openai_params, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"openai_params\"}") as models.schemas.AiLlmEndpointParams;
  assert.equal((known as Record<string, unknown>)["type"], "openai_params");
  const unknown: models.schemas.AiLlmEndpointParams = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.AiTaxonomySource dispatches on type — known taxonomy, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"taxonomy\"}") as models.schemas.AiTaxonomySource;
  assert.equal((known as Record<string, unknown>)["type"], "taxonomy");
  const unknown: models.schemas.AiTaxonomySource = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.AiTextGenAgent dispatches on type — known ai_agent_id, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"ai_agent_id\"}") as models.schemas.AiTextGenAgent;
  assert.equal((known as Record<string, unknown>)["type"], "ai_agent_id");
  const unknown: models.schemas.AiTextGenAgent = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.AppItemAssociatedItem dispatches on type — known file, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"file\"}") as models.schemas.AppItemAssociatedItem;
  assert.equal((known as Record<string, unknown>)["type"], "file");
  const unknown: models.schemas.AppItemAssociatedItem = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.CollaborationAccessGrantee dispatches on type — known user, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"user\"}") as models.schemas.CollaborationAccessGrantee;
  assert.equal((known as Record<string, unknown>)["type"], "user");
  const unknown: models.schemas.CollaborationAccessGrantee = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.CollaborationItem dispatches on type — known file, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"file\"}") as models.schemas.CollaborationItem;
  assert.equal((known as Record<string, unknown>)["type"], "file");
  const unknown: models.schemas.CollaborationItem = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.Item dispatches on type — known file, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"file\"}") as models.schemas.Item;
  assert.equal((known as Record<string, unknown>)["type"], "file");
  const unknown: models.schemas.Item = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.MetadataQueryResultItem dispatches on type — known file, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"file\"}") as models.schemas.MetadataQueryResultItem;
  assert.equal((known as Record<string, unknown>)["type"], "file");
  const unknown: models.schemas.MetadataQueryResultItem = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.RecentItemResource dispatches on type — known file, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"file\"}") as models.schemas.RecentItemResource;
  assert.equal((known as Record<string, unknown>)["type"], "file");
  const unknown: models.schemas.RecentItemResource = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.Resource dispatches on type — known folder, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"folder\"}") as models.schemas.Resource;
  assert.equal((known as Record<string, unknown>)["type"], "folder");
  const unknown: models.schemas.Resource = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.SearchResultItem dispatches on type — known file, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"file\"}") as models.schemas.SearchResultItem;
  assert.equal((known as Record<string, unknown>)["type"], "file");
  const unknown: models.schemas.SearchResultItem = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.SearchResultsResponse dispatches on type — known search_results_items, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"search_results_items\"}") as models.schemas.SearchResultsResponse;
  assert.equal((known as Record<string, unknown>)["type"], "search_results_items");
  const unknown: models.schemas.SearchResultsResponse = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.SearchResultWithSharedLinkItem dispatches on type — known file, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"file\"}") as models.schemas.SearchResultWithSharedLinkItem;
  assert.equal((known as Record<string, unknown>)["type"], "file");
  const unknown: models.schemas.SearchResultWithSharedLinkItem = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.HubAccessGrantee dispatches on type — known user, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"user\"}") as models.schemas.HubAccessGrantee;
  assert.equal((known as Record<string, unknown>)["type"], "user");
  const unknown: models.schemas.HubAccessGrantee = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.HubDocumentBlockEntry dispatches on type — known paragraph, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"paragraph\"}") as models.schemas.HubDocumentBlockEntry;
  assert.equal((known as Record<string, unknown>)["type"], "paragraph");
  const unknown: models.schemas.HubDocumentBlockEntry = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.HubItemReference dispatches on type — known file, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"file\"}") as models.schemas.HubItemReference;
  assert.equal((known as Record<string, unknown>)["type"], "file");
  const unknown: models.schemas.HubItemReference = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.ShieldListContent dispatches on type — known country, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"country\"}") as models.schemas.ShieldListContent;
  assert.equal((known as Record<string, unknown>)["type"], "country");
  const unknown: models.schemas.ShieldListContent = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});

test('schemas.ShieldListContentRequest dispatches on type — known country, unknown retained', () => {
  const known = JSON.parse("{\"type\":\"country\"}") as models.schemas.ShieldListContentRequest;
  assert.equal((known as Record<string, unknown>)["type"], "country");
  const unknown: models.schemas.ShieldListContentRequest = { "type": '__gantry_unknown__' };
  assert.equal((unknown as Record<string, unknown>)["type"], '__gantry_unknown__');
});
